In [5]:
import pandas as pd
import clickhouse_connect
from datetime import datetime





import os
from dotenv import load_dotenv

load_dotenv()

True

In [6]:

# создаём клиент
# client = clickhouse_connect.get_client(
#     host= os.getenv("CLICKHOUSE_HOST") ,   # замени на свой хост/адрес
#     port= os.getenv("CLICKHOUSE_PORT"),
#     username=  os.getenv("CLICKHOUSE_USER"),
#     password= os.getenv("CLICKHOUSE_PASSWORD")
# )
client = clickhouse_connect.get_client(
    host="84.201.160.255",   # замени на свой хост/адрес
    port=8123,
    username="peter",
    password="1234"
)

In [6]:
# SQL-запрос
query = "SELECT * FROM mailkb.emails ORDER BY id DESC LIMIT 5"

# вернуть сразу DataFrame
df = client.query_df(query)

In [26]:
df = df.iloc[2]['body_text']

In [9]:
## импортируем либы для структурированного ответа

from pydantic import BaseModel, Field
from langchain.agents import create_agent
from typing import List



class MailInfo(BaseModel):
    """Contact information for a person."""
    topic: str = Field(..., description="The name of the mail ")
    email: str = Field(..., description="The email address of the persons of the mail")

class MailChainInfo(BaseModel):
    emails: List[MailInfo] = Field(description='mail chain info')

agent = create_agent(
    model="gpt-5",
    response_format=MailChainInfo  # Auto-selects ProviderStrategy
)

# result = agent.invoke({
#     "messages": [{"role": "user", "content": "Extract contact info from: {}"}]
# })
#
# print(result["structured_response"])
# ContactInfo(name='John Doe', email='john@example.com', phone='(555) 123-4567')

In [12]:
df['body_text'][0]

'Это МТЗ?\r\n________________________________\r\n\r\nОт: Ilya M Sergeev <Ilya.Sergeev@ru.ey.com>\r\nОтправлено: воскресенье, 19 августа 2018 г. 14:47\r\nКому: Maxim P Lyutov <Maxim.Lyutov@ru.ey.com>,Chigvintsev Anton <anton.chigvintsev@bearingpoint.ru>,"Kozlov Yuriy(CE)" <ce-yuriy.kozlov@bearingpoint.ru>,Алексей Алмакаев <A.Almakaev@agrohold.ru>,Zhanna L Vakhrusheva <Zhanna.L.Vakhrusheva@ru.ey.com>,Алексей Филимончук <A.Filimonchuk@agrohold.ru>,Андрей Кравченко <A.Kravchenko@agrohold.ru>,Андрей Николаевич Петров <A.N.Petrov@agrohold.ru>,Yuri A Denisov <Yuri.Denisov@ru.ey.com>,Dmitry V Karpov <Dmitry.Karpov@ru.ey.com>,Alexey S Fedoseev <Alexey.Fedoseev@ru.ey.com>,Валерий Бражников <V.Brazhnikov@agrohold.ru>,Vadim Kotenko <V.Kotenko@agrohold.ru>,"Scherbakov Andrey(CE)" <ce-andrey.scherbakov@bearingpoint.ru>,Андрей Владимирович Самойленко <AV.Samoylenko@agrohold.ru>,Вадим Просолупов <V.Prosolupov@agrohold.ru>,Александр Игоревич Александров <a.i.aleksandrov@agrohold.ru>,Иван Лосев <I.Losev@agrohold.ru>,Александр Пчелин <A.Pchelin@agrohold.ru>,Карина Кувшинова <K.Kuvshinova@agrohold.ru>,Екатерина Кармишина <E.Khamina@agrohold.ru>,Дмитрий Зинков <D.Zinkov@agrohold.ru>,Александра Горелова <A.Gorelova@agrohold.ru>,WG Sklad 21 <sklad-rst@agrohold.ru>,Владимир Викторович Скворцов <vv.skvortsov@agrohold.ru>,Надежда Иванова <ivanova@agrohold.ru>,Олеся Любакова <Zakurdaeva@agrohold.ru>,Сергей Лынов <S.Lynov@agrohold.ru>,Денис Леонидович Олейник <dl.oleynik@agrohold.ru>,Алексей Потапов <A.M.Potapov@agrohold.ru>,Денис Кисарин <D.Kisarin@agrohold.ru>,Ренат Халилюлин <Halilulin@agrohold.ru>,Дмитрий Топоров <D.Toporov@agrohold.ru>,Владимир Лавейкин <V.Laveykin@agrohold.ru>,Павел Прокашев <P.Prokashev@agrohold.ru>,Егор Смирнов <E.Smirnov@agrohold.ru>,Екатерина Евгеньевна Полякова <E.E.Polyakova@agrohold.ru>,Павел Шабанов <P.Shabanov@agrohold.ru>,Анна Себелева <A.Sebeleva@agrohold.ru>,Василий Соляник <V.Solyanik@agrohold.ru>,Алексей Вадимович Алексеев <A.Alexeyev@agrohold.ru>,Ivan S Butyagin <ivan.butyagin@ru.ey.com>,Anna V Turygina <Anna.Turygina@ru.ey.com>,Evgeny L Kuznetsov <Evgeny.Kuznetsov@ru.ey.com>,Alexander S Larin <Alexander.Larin@ru.ey.com>,Igor M Trifonov <Igor.Trifonov@ru.ey.com>,Nikita A Savkin <nikita.savkin@ru.ey.com>,Sergey Popov <popov.sergey@bearingpoint.ru>,Artem I Krasnoperov <Artem.Krasnoperov@ru.ey.com>,Александр Жуков <alexander.zhukov@solmix.spb.ru>,Egorova Tatiana <tatiana.egorova@bearingpoint.ru>,Tkachenko Sergey <sergey.tkachenko@bearingpoint.ru>,"Zhukov Alexander(CE)" <ce-alexander.zhukov@bearingpoint.ru>,Анна Найда <A.Naida@agrohold.ru>,Павел Болотников <P.Bolotnikov@agrohold.ru>,Евгения Владимировна Гончарова <E.V.Goncharova@agrohold.ru>,Наталья Межина <N.Megina@agrohold.ru>,Альбина Беспарточная <a.bespartochnaya@agrohold.ru>,Анна Клименкова <A.Klimenkova@agrohold.ru>,Дарья Юркевич <D.Yurkevich@agrohold.ru>,Екатерина Еременко <E.Yeremenko@agrohold.ru>,Светлана Смывина <Kshnaikina@agrohold.ru>,Анна Извекова <a.izvekova@agrohold.ru>,Максим Лимов <M.Limov@agrohold.ru>,Ксения Боброва <k.bobrova@agrohold.ru>,Khadzhieva Kristina <kristina.khadzhieva@bearingpoint.ru>,Bektur Kazakbaev <Bektur.Kazakbaev@ru.ey.com>,Zyryanova Nadezhda <nadezhda.zyryanova@bearingpoint.ru>,Kosmynin Egor <egor.kosmynin@bearingpoint.ru>,"Batyrshin Rustam(CE)" <ce-rustam.batyrshin@bearingpoint.ru>,Levanovich Vladislav <vladislav.levanovich@bearingpoint.ru>,Makarenko Aleksei <aleksei.makarenko@bearingpoint.ru>,Krashchenko Oleg <oleg.krashchenko@bearingpoint.ru>,Aleksandr V Muravev <Aleksandr.Muravev@ru.ey.com>,Viacheslav A Polukhin <Viacheslav.Polukhin@ru.ey.com>,Dmitry I Zhulev <Dmitry.Zhulev@ru.ey.com>,David V Zakarian <David.Zakarian@ru.ey.com>,Dimitriy Karpov <dimitriy.karpov@gmail.com>,Petr S Lobach <Petr.Lobach@ru.ey.com>,Liana R Sadykova <Liana.Sadykova@ru.ey.com>,Dondukov Ivan <ivan.dondukov@bearingpoint.ru>,Balyabina Anna <anna.balyabina@bearingpoint.ru>,Fayzullaeva Sabina <sabina.fayzullaeva@bearingpoint.ru>,Isaev Yury <yury.isaev@bearingpoint.ru>,Timoshin Andrey <andrey.timoshin@bearingpoint.ru>,Ostrik Petr <petr.ostrik@bearingpoint.ru>,Te Alexandr <alexandr.te@bearingpoint.ru>,Artem V Rasstanaev <Artem.Rasstanaev@ru.ey.com>,Fedor B Ermolaev <Fedor.Ermolaev@ru.ey.com>,Stanislav E Cherkassky <Stanislav.Cherkassky@ru.ey.com>,Alsu R Golubyatnikova <Alsu.Fatykhova@ru.ey.com>,Mikhail V Vasilov <Mikhail.Vasilov@ru.ey.com>,Nikita S Galiarda <Nikita.Galiarda@ru.ey.com>,Elmira A Ufimskaia <Elmira.Ufimskaia@ru.ey.com>,Vladislav E Kutka <Vladislav.Kutka@ru.ey.com>,Stanislav S Solovyanenko <Stanislav.Solovyanenko@ru.ey.com>,Petr S Sharygin <Petr.Sharygin@ru.ey.com>,"Prusov Mikhail (CE)" <ce-mikhail.prusov@bearingpoint.ru>\r\nТема: RE: Запуск SAP: 6 Филиалов, график координации перехода\r\n\r\n\r\n\r\n\r\nНет по 35-ти позициям по поставкам:\r\n\r\n1800010786\r\n\r\n1800010771\r\n\r\n1800010774\r\n\r\n1800010778\r\n\r\n1800010791\r\n\r\n \r\n\r\nС уважением,\r\n\r\n\r\n\r\nИлья Сергеев | Группа «Интеграция с ФГИС Меркурий» |\r\n\r\nПроект «Эволюция бизнеса»\r\n\r\ne-mail: Ilya.Sergeev@ru.ey.com <mailto:Ilya.Sergeev@ru.ey.com> \r\n\r\nмоб. +7-967-129-92-98\r\n\r\n \r\n\r\n \r\n\r\nFrom: Maxim P Lyutov \r\nSent: Sunday, August 19, 2018 2:38 PM\r\nTo: Chigvintsev Anton <anton.chigvintsev@bearingpoint.ru>; Kozlov Yuriy(CE) <ce-yuriy.kozlov@bearingpoint.ru>; Алексей Алмакаев <A.Almakaev@agrohold.ru>; Zhanna L Vakhrusheva <Zhanna.L.Vakhrusheva@ru.ey.com>; Алексей Филимончук <A.Filimonchuk@agrohold.ru>; Андрей Кравченко <A.Kravchenko@agrohold.ru>; Андрей Николаевич Петров <A.N.Petrov@agrohold.ru>; Yuri A Denisov <Yuri.Denisov@ru.ey.com>; Dmitry V Karpov <Dmitry.Karpov@ru.ey.com>; Alexey S Fedoseev <Alexey.Fedoseev@ru.ey.com>; Валерий Бражников <V.Brazhnikov@agrohold.ru>; Vadim Kotenko <V.Kotenko@agrohold.ru>; Scherbakov Andrey(CE) <ce-andrey.scherbakov@bearingpoint.ru>; Андрей Владимирович Самойленко <AV.Samoylenko@agrohold.ru>; Вадим Просолупов <V.Prosolupov@agrohold.ru>; Александр Игоревич Александров <a.i.aleksandrov@agrohold.ru>; Иван Лосев <I.Losev@agrohold.ru>; Александр Пчелин <A.Pchelin@agrohold.ru>; Карина Кувшинова <K.Kuvshinova@agrohold.ru>; Екатерина Кармишина <E.Khamina@agrohold.ru>; Дмитрий Зинков <D.Zinkov@agrohold.ru>; Александра Горелова <A.Gorelova@agrohold.ru>; WG Sklad 21 <sklad-rst@agrohold.ru>; Владимир Викторович Скворцов <vv.skvortsov@agrohold.ru>; Надежда Иванова <ivanova@agrohold.ru>; Олеся Любакова <Zakurdaeva@agrohold.ru>; Сергей Лынов <S.Lynov@agrohold.ru>; Денис Леонидович Олейник <dl.oleynik@agrohold.ru>; Алексей Потапов <A.M.Potapov@agrohold.ru>; Денис Кисарин <D.Kisarin@agrohold.ru>; Ренат Халилюлин <Halilulin@agrohold.ru>; Дмитрий Топоров <D.Toporov@agrohold.ru>; Владимир Лавейкин <V.Laveykin@agrohold.ru>; Павел Прокашев <P.Prokashev@agrohold.ru>; Егор Смирнов <E.Smirnov@agrohold.ru>; Екатерина Евгеньевна Полякова <E.E.Polyakova@agrohold.ru>; Павел Шабанов <P.Shabanov@agrohold.ru>; Анна Себелева <A.Sebeleva@agrohold.ru>; Василий Соляник <V.Solyanik@agrohold.ru>; Алексей Вадимович Алексеев <A.Alexeyev@agrohold.ru>; Ivan S Butyagin <ivan.butyagin@ru.ey.com>; Anna V Turygina <Anna.Turygina@ru.ey.com>; Evgeny L Kuznetsov <Evgeny.Kuznetsov@ru.ey.com>; Alexander S Larin <Alexander.Larin@ru.ey.com>; Igor M Trifonov <Igor.Trifonov@ru.ey.com>; Nikita A Savkin <nikita.savkin@ru.ey.com>; Sergey Popov <popov.sergey@bearingpoint.ru>; Artem I Krasnoperov <Artem.Krasnoperov@ru.ey.com>; Александр Жуков <alexander.zhukov@solmix.spb.ru>; Egorova Tatiana <tatiana.egorova@bearingpoint.ru>; Tkachenko Sergey <sergey.tkachenko@bearingpoint.ru>; Zhukov Alexander(CE) <ce-alexander.zhukov@bearingpoint.ru>; Анна Найда <A.Naida@agrohold.ru>; Павел Болотников <P.Bolotnikov@agrohold.ru>; Евгения Владимировна Гончарова <E.V.Goncharova@agrohold.ru>; Наталья Межина <N.Megina@agrohold.ru>; Альбина Беспарточная <a.bespartochnaya@agrohold.ru>; Анна Клименкова <A.Klimenkova@agrohold.ru>; Дарья Юркевич <D.Yurkevich@agrohold.ru>; Екатерина Еременко <E.Yeremenko@agrohold.ru>; Светлана Смывина <Kshnaikina@agrohold.ru>; Анна Извекова <a.izvekova@agrohold.ru>; Максим Лимов <M.Limov@agrohold.ru>; Ксения Боброва <k.bobrova@agrohold.ru>; Ilya M Sergeev <Ilya.Sergeev@ru.ey.com>; Khadzhieva Kristina <kristina.khadzhieva@bearingpoint.ru>; Bektur Kazakbaev <Bektur.Kazakbaev@ru.ey.com>; Zyryanova Nadezhda <nadezhda.zyryanova@bearingpoint.ru>; Kosmynin Egor <egor.kosmynin@bearingpoint.ru>; Batyrshin Rustam(CE) <ce-rustam.batyrshin@bearingpoint.ru>; Levanovich Vladislav <vladislav.levanovich@bearingpoint.ru>; Makarenko Aleksei <aleksei.makarenko@bearingpoint.ru>; Krashchenko Oleg <oleg.krashchenko@bearingpoint.ru>; Aleksandr V Muravev <Aleksandr.Muravev@ru.ey.com>; Viacheslav A Polukhin <Viacheslav.Polukhin@ru.ey.com>; Dmitry I Zhulev <Dmitry.Zhulev@ru.ey.com>; David V Zakarian <David.Zakarian@ru.ey.com>; Dimitriy Karpov <dimitriy.karpov@gmail.com>; Petr S Lobach <Petr.Lobach@ru.ey.com>; Liana R Sadykova <Liana.Sadykova@ru.ey.com>; Dondukov Ivan <ivan.dondukov@bearingpoint.ru>; Balyabina Anna <anna.balyabina@bearingpoint.ru>; Fayzullaeva Sabina <sabina.fayzullaeva@bearingpoint.ru>; Isaev Yury <yury.isaev@bearingpoint.ru>; Timoshin Andrey <andrey.timoshin@bearingpoint.ru>; Ostrik Petr <petr.ostrik@bearingpoint.ru>; Te Alexandr <alexandr.te@bearingpoint.ru>; Artem V Rasstanaev <Artem.Rasstanaev@ru.ey.com>; Fedor B Ermolaev <Fedor.Ermolaev@ru.ey.com>; Stanislav E Cherkassky <Stanislav.Cherkassky@ru.ey.com>; Alsu R Golubyatnikova <Alsu.Fatykhova@ru.ey.com>; Mikhail V Vasilov <Mikhail.Vasilov@ru.ey.com>; Nikita S Galiarda <Nikita.Galiarda@ru.ey.com>; Elmira A Ufimskaia <Elmira.Ufimskaia@ru.ey.com>; Vladislav E Kutka <Vladislav.Kutka@ru.ey.com>; Stanislav S Solovyanenko <Stanislav.Solovyanenko@ru.ey.com>; Petr S Sharygin <Petr.Sharygin@ru.ey.com>; Prusov Mikhail (CE) <ce-mikhail.prusov@bearingpoint.ru>\r\nSubject: RE: Запуск SAP: 6 Филиалов, график координации перехода\r\n\r\n \r\n\r\nИлья Сергеев, проверь пожалуйста наличие всд во всех поставках.\r\n\r\n________________________________\r\n\r\nОт: Chigvintsev Anton <anton.chigvintsev@bearingpoint.ru <mailto:anton.chigvintsev@bearingpoint.ru> >\r\nОтправлено: воскресенье, 19 августа 2018 г. 14:12\r\nКому: "Kozlov Yuriy(CE)" <ce-yuriy.kozlov@bearingpoint.ru <mailto:ce-yuriy.kozlov@bearingpoint.ru> >,Алексей Алмакаев <A.Almakaev@agrohold.ru <mailto:A.Almakaev@agrohold.ru> >,Zhanna L Vakhrusheva <Zhanna.L.Vakhrusheva@ru.ey.com <mailto:Zhanna.L.Vakhrusheva@ru.ey.com> >,Алексей Филимончук <A.Filimonchuk@agrohold.ru <mailto:A.Filimonchuk@agrohold.ru> >,Андрей Кравченко <A.Kravchenko@agrohold.ru <mailto:A.Kravchenko@agrohold.ru> >,Андрей Николаевич Петров <A.N.Petrov@agrohold.ru <mailto:A.N.Petrov@agrohold.ru> >,Yuri A Denisov <Yuri.Denisov@ru.ey.com <mailto:Yuri.Denisov@ru.ey.com> >,Dmitry V Karpov <Dmitry.Karpov@ru.ey.com <mailto:Dmitry.Karpov@ru.ey.com> >,Alexey S Fedoseev <Alexey.Fedoseev@ru.ey.com <mailto:Alexey.Fedoseev@ru.ey.com> >,Валерий Бражников <V.Brazhnikov@agrohold.ru <mailto:V.Brazhnikov@agrohold.ru> >,Vadim Kotenko <V.Kotenko@agrohold.ru <mailto:V.Kotenko@agrohold.ru> >,"Scherbakov Andrey(CE)" <ce-andrey.scherbakov@bearingpoint.ru <mailto:ce-andrey.scherbakov@bearingpoint.ru> >,Андрей Владимирович Самойленко <AV.Samoylenko@agrohold.ru <mailto:AV.Samoylenko@agrohold.ru> >,Вадим Просолупов <V.Prosolupov@agrohold.ru <mailto:V.Prosolupov@agrohold.ru> >,Александр Игоревич Александров <a.i.aleksandrov@agrohold.ru <mailto:a.i.aleksandrov@agrohold.ru> >,Иван Лосев <I.Losev@agrohold.ru <mailto:I.Losev@agrohold.ru> >,Александр Пчелин <A.Pchelin@agrohold.ru <mailto:A.Pchelin@agrohold.ru> >,Карина Кувшинова <K.Kuvshinova@agrohold.ru <mailto:K.Kuvshinova@agrohold.ru> >,Екатерина Кармишина <E.Khamina@agrohold.ru <mailto:E.Khamina@agrohold.ru> >,Дмитрий Зинков <D.Zinkov@agrohold.ru <mailto:D.Zinkov@agrohold.ru> >,Александра Горелова <A.Gorelova@agrohold.ru <mailto:A.Gorelova@agrohold.ru> >,WG Sklad 21 <sklad-rst@agrohold.ru <mailto:sklad-rst@agrohold.ru> >,Владимир Викторович Скворцов <vv.skvortsov@agrohold.ru <mailto:vv.skvortsov@agrohold.ru> >,Надежда Иванова <ivanova@agrohold.ru <mailto:ivanova@agrohold.ru> >,Олеся Любакова <Zakurdaeva@agrohold.ru <mailto:Zakurdaeva@agrohold.ru> >,Сергей Лынов <S.Lynov@agrohold.ru <mailto:S.Lynov@agrohold.ru> >,Денис Леонидович Олейник <dl.oleynik@agrohold.ru <mailto:dl.oleynik@agrohold.ru> >,Алексей Потапов <A.M.Potapov@agrohold.ru <mailto:A.M.Potapov@agrohold.ru> >,Денис Кисарин <D.Kisarin@agrohold.ru <mailto:D.Kisarin@agrohold.ru> >,Ренат Халилюлин <Halilulin@agrohold.ru <mailto:Halilulin@agrohold.ru> >,Дмитрий Топоров <D.Toporov@agrohold.ru <mailto:D.Toporov@agrohold.ru> >,Владимир Лавейкин <V.Laveykin@agrohold.ru <mailto:V.Laveykin@agrohold.ru> >,Павел Прокашев <P.Prokashev@agrohold.ru <mailto:P.Prokashev@agrohold.ru> >,Егор Смирнов <E.Smirnov@agrohold.ru <mailto:E.Smirnov@agrohold.ru> >,Екатерина Евгеньевна Полякова <E.E.Polyakova@agrohold.ru <mailto:E.E.Polyakova@agrohold.ru> >,Павел Шабанов <P.Shabanov@agrohold.ru <mailto:P.Shabanov@agrohold.ru> >,Анна Себелева <A.Sebeleva@agrohold.ru <mailto:A.Sebeleva@agrohold.ru> >,Василий Соляник <V.Solyanik@agrohold.ru <mailto:V.Solyanik@agrohold.ru> >,Алексей Вадимович Алексеев <A.Alexeyev@agrohold.ru <mailto:A.Alexeyev@agrohold.ru> >,Ivan S Butyagin <ivan.butyagin@ru.ey.com <mailto:ivan.butyagin@ru.ey.com> >,Anna V Turygina <Anna.Turygina@ru.ey.com <mailto:Anna.Turygina@ru.ey.com> >,Evgeny L Kuznetsov <Evgeny.Kuznetsov@ru.ey.com <mailto:Evgeny.Kuznetsov@ru.ey.com> >,Alexander S Larin <Alexander.Larin@ru.ey.com <mailto:Alexander.Larin@ru.ey.com> >,Igor M Trifonov <Igor.Trifonov@ru.ey.com <mailto:Igor.Trifonov@ru.ey.com> >,Nikita A Savkin <nikita.savkin@ru.ey.com <mailto:nikita.savkin@ru.ey.com> >,Sergey Popov <popov.sergey@bearingpoint.ru <mailto:popov.sergey@bearingpoint.ru> >,Artem I Krasnoperov <Artem.Krasnoperov@ru.ey.com <mailto:Artem.Krasnoperov@ru.ey.com> >,Александр Жуков <alexander.zhukov@solmix.spb.ru <mailto:alexander.zhukov@solmix.spb.ru> >,Egorova Tatiana <tatiana.egorova@bearingpoint.ru <mailto:tatiana.egorova@bearingpoint.ru> >,Tkachenko Sergey <sergey.tkachenko@bearingpoint.ru <mailto:sergey.tkachenko@bearingpoint.ru> >,Maxim P Lyutov <Maxim.Lyutov@ru.ey.com <mailto:Maxim.Lyutov@ru.ey.com> >,"Zhukov Alexander(CE)" <ce-alexander.zhukov@bearingpoint.ru <mailto:ce-alexander.zhukov@bearingpoint.ru> >,Анна Найда <A.Naida@agrohold.ru <mailto:A.Naida@agrohold.ru> >,Павел Болотников <P.Bolotnikov@agrohold.ru <mailto:P.Bolotnikov@agrohold.ru> >,Евгения Владимировна Гончарова <E.V.Goncharova@agrohold.ru <mailto:E.V.Goncharova@agrohold.ru> >,Наталья Межина <N.Megina@agrohold.ru <mailto:N.Megina@agrohold.ru> >,Альбина Беспарточная <a.bespartochnaya@agrohold.ru <mailto:a.bespartochnaya@agrohold.ru> >,Анна Клименкова <A.Klimenkova@agrohold.ru <mailto:A.Klimenkova@agrohold.ru> >,Дарья Юркевич <D.Yurkevich@agrohold.ru <mailto:D.Yurkevich@agrohold.ru> >,Екатерина Еременко <E.Yeremenko@agrohold.ru <mailto:E.Yeremenko@agrohold.ru> >,Денис Леонидович Олейник <dl.oleynik@agrohold.ru <mailto:dl.oleynik@agrohold.ru> >,Сергей Лынов <S.Lynov@agrohold.ru <mailto:S.Lynov@agrohold.ru> >,Денис Кисарин <D.Kisarin@agrohold.ru <mailto:D.Kisarin@agrohold.ru> >,Алексей Потапов <A.M.Potapov@agrohold.ru <mailto:A.M.Potapov@agrohold.ru> >,Светлана Смывина <Kshnaikina@agrohold.ru <mailto:Kshnaikina@agrohold.ru> >,Олеся Любакова <Zakurdaeva@agrohold.ru <mailto:Zakurdaeva@agrohold.ru> >,Екатерина Кармишина <E.Khamina@agrohold.ru <mailto:E.Khamina@agrohold.ru> >,Анна Извекова <a.izvekova@agrohold.ru <mailto:a.izvekova@agrohold.ru> >,Максим Лимов <M.Limov@agrohold.ru <mailto:M.Limov@agrohold.ru> >,Павел Шабанов <P.Shabanov@agrohold.ru <mailto:P.Shabanov@agrohold.ru> >,Егор Смирнов <E.Smirnov@agrohold.ru <mailto:E.Smirnov@agrohold.ru> >,Ксения Боброва <k.bobrova@agrohold.ru <mailto:k.bobrova@agrohold.ru> >,Анна Себелева <A.Sebeleva@agrohold.ru <mailto:A.Sebeleva@agrohold.ru> >,Василий Соляник <V.Solyanik@agrohold.ru <mailto:V.Solyanik@agrohold.ru> >,Ilya M Sergeev <Ilya.Sergeev@ru.ey.com <mailto:Ilya.Sergeev@ru.ey.com> >,Khadzhieva Kristina <kristina.khadzhieva@bearingpoint.ru <mailto:kristina.khadzhieva@bearingpoint.ru> >,Bektur Kazakbaev <Bektur.Kazakbaev@ru.ey.com <mailto:Bektur.Kazakbaev@ru.ey.com> >,Zyryanova Nadezhda <nadezhda.zyryanova@bearingpoint.ru <mailto:nadezhda.zyryanova@bearingpoint.ru> >,Kosmynin Egor <egor.kosmynin@bearingpoint.ru <mailto:egor.kosmynin@bearingpoint.ru> >,"Batyrshin Rustam(CE)" <ce-rustam.batyrshin@bearingpoint.ru <mailto:ce-rustam.batyrshin@bearingpoint.ru> >,Levanovich Vladislav <vladislav.levanovich@bearingpoint.ru <mailto:vladislav.levanovich@bearingpoint.ru> >,Makarenko Aleksei <aleksei.makarenko@bearingpoint.ru <mailto:aleksei.makarenko@bearingpoint.ru> >,Krashchenko Oleg <oleg.krashchenko@bearingpoint.ru <mailto:oleg.krashchenko@bearingpoint.ru> >,Aleksandr V Muravev <Aleksandr.Muravev@ru.ey.com <mailto:Aleksandr.Muravev@ru.ey.com> >,Alexander S Larin <Alexander.Larin@ru.ey.com <mailto:Alexander.Larin@ru.ey.com> >,Viacheslav A Polukhin <Viacheslav.Polukhin@ru.ey.com <mailto:Viacheslav.Polukhin@ru.ey.com> >,Dmitry I Zhulev <Dmitry.Zhulev@ru.ey.com <mailto:Dmitry.Zhulev@ru.ey.com> >,Igor M Trifonov <Igor.Trifonov@ru.ey.com <mailto:Igor.Trifonov@ru.ey.com> >,David V Zakarian <David.Zakarian@ru.ey.com <mailto:David.Zakarian@ru.ey.com> >,Dimitriy Karpov <dimitriy.karpov@gmail.com <mailto:dimitriy.karpov@gmail.com> >,Petr S Lobach <Petr.Lobach@ru.ey.com <mailto:Petr.Lobach@ru.ey.com> >,Liana R Sadykova <Liana.Sadykova@ru.ey.com <mailto:Liana.Sadykova@ru.ey.com> >,Dondukov Ivan <ivan.dondukov@bearingpoint.ru <mailto:ivan.dondukov@bearingpoint.ru> >,Balyabina Anna <anna.balyabina@bearingpoint.ru <mailto:anna.balyabina@bearingpoint.ru> >,Egorova Tatiana <tatiana.egorova@bearingpoint.ru <mailto:tatiana.egorova@bearingpoint.ru> >,"Zhukov Alexander(CE)" <ce-alexander.zhukov@bearingpoint.ru <mailto:ce-alexander.zhukov@bearingpoint.ru> >,Fayzullaeva Sabina <sabina.fayzullaeva@bearingpoint.ru <mailto:sabina.fayzullaeva@bearingpoint.ru> >,Dondukov Ivan <ivan.dondukov@bearingpoint.ru <mailto:ivan.dondukov@bearingpoint.ru> >,Balyabina Anna <anna.balyabina@bearingpoint.ru <mailto:anna.balyabina@bearingpoint.ru> >,Egorova Tatiana <tatiana.egorova@bearingpoint.ru <mailto:tatiana.egorova@bearingpoint.ru> >,"Zhukov Alexander(CE)" <ce-alexander.zhukov@bearingpoint.ru <mailto:ce-alexander.zhukov@bearingpoint.ru> >,Fayzullaeva Sabina <sabina.fayzullaeva@bearingpoint.ru <mailto:sabina.fayzullaeva@bearingpoint.ru> >,Dondukov Ivan <ivan.dondukov@bearingpoint.ru <mailto:ivan.dondukov@bearingpoint.ru> >,Balyabina Anna <anna.balyabina@bearingpoint.ru <mailto:anna.balyabina@bearingpoint.ru> >,Egorova Tatiana <tatiana.egorova@bearingpoint.ru <mailto:tatiana.egorova@bearingpoint.ru> >,"Zhukov Alexander(CE)" <ce-alexander.zhukov@bearingpoint.ru <mailto:ce-alexander.zhukov@bearingpoint.ru> >,Isaev Yury <yury.isaev@bearingpoint.ru <mailto:yury.isaev@bearingpoint.ru> >,Dondukov Ivan <ivan.dondukov@bearingpoint.ru <mailto:ivan.dondukov@bearingpoint.ru> >,Balyabina Anna <anna.balyabina@bearingpoint.ru <mailto:anna.balyabina@bearingpoint.ru> >,Egorova Tatiana <tatiana.egorova@bearingpoint.ru <mailto:tatiana.egorova@bearingpoint.ru> >,"Zhukov Alexander(CE)" <ce-alexander.zhukov@bearingpoint.ru <mailto:ce-alexander.zhukov@bearingpoint.ru> >,Isaev Yury <yury.isaev@bearingpoint.ru <mailto:yury.isaev@bearingpoint.ru> >,Timoshin Andrey <andrey.timoshin@bearingpoint.ru <mailto:andrey.timoshin@bearingpoint.ru> >,Ostrik Petr <petr.ostrik@bearingpoint.ru <mailto:petr.ostrik@bearingpoint.ru> >,Isaev Yury <yury.isaev@bearingpoint.ru <mailto:yury.isaev@bearingpoint.ru> >,Te Alexandr <alexandr.te@bearingpoint.ru <mailto:alexandr.te@bearingpoint.ru> >,Evgeny L Kuznetsov <Evgeny.Kuznetsov@ru.ey.com <mailto:Evgeny.Kuznetsov@ru.ey.com> >,Krashchenko Oleg <oleg.krashchenko@bearingpoint.ru <mailto:oleg.krashchenko@bearingpoint.ru> >,"Batyrshin Rustam(CE)" <ce-rustam.batyrshin@bearingpoint.ru 

In [10]:
result = agent.invoke({
    "messages": [
        {
            "role": "user",
            "content": f"""Начни обработку строки и вытащи темы писем и email адреса:

{df['body_text'][0]}   """

        }
    ]
})

report = result["messages"][-1].content
print(report)

{"emails":[{"topic":"RE: Запуск SAP: 6 Филиалов, график координации перехода","email":"Ilya.Sergeev@ru.ey.com"},{"topic":"RE: Запуск SAP: 6 Филиалов, график координации перехода","email":"Maxim.Lyutov@ru.ey.com"},{"topic":"RE: Запуск SAP: 6 Филиалов, график координации перехода","email":"anton.chigvintsev@bearingpoint.ru"},{"topic":"Re: Запуск SAP: 6 Филиалов, график координации перехода","email":"ce-yuriy.kozlov@bearingpoint.ru"},{"topic":"RE: Запуск SAP: 6 Филиалов, график координации перехода","email":"A.Almakaev@agrohold.ru"},{"topic":"RE: Запуск SAP: 6 Филиалов, график координации перехода","email":"A.Filimonchuk@agrohold.ru"},{"topic":"RE: Запуск SAP: 6 Филиалов, график координации перехода","email":"A.Kravchenko@agrohold.ru"},{"topic":"RE: Запуск SAP: 6 Филиалов, график координации перехода","email":"Yuri.Denisov@ru.ey.com"},{"topic":"RE: Запуск SAP: 6 Филиалов, график координации перехода","email":"Alexey.Fedoseev@ru.ey.com"},{"topic":"Re: Запуск SAP: 6 Филиалов, график координации перехода","email":"ce-andrey.scherbakov@bearingpoint.ru"},{"topic":"Запуск SAP: 6 Филиалов, график координации перехода","email":"Yuri.Denisov@ru.ey.com"}]}

In [12]:
Structured output


ключевые поинты
emailы все

SyntaxError: invalid syntax (734425773.py, line 1)

### Агент по очистке письма в диалогах

In [62]:
from pydantic import BaseModel, Field
from langchain.agents import create_agent
from clickhouse_connect import get_client
import hashlib
import time

In [50]:
# --- structured output schema ---

class CleanBody(BaseModel):
    """Cleaned body of an email."""

    body_clean: str = Field(
        ...,
        description="Top-level email text without quoted history, headers, or signatures"
    )

# --- prompt for the LLM ---

PROMPT = """
You clean email bodies.

Task:
Extract ONLY the new message written by the sender.

Remove:
- quoted history
- repeated headers (From, Sent, Subject)
- signatures
- reply separators

Keep only the actual message content.

Return JSON matching the schema.
"""

# --- create LLM agent ---

agent = create_agent(
    model="deepseek-chat",
    response_format=CleanBody
)

In [57]:
# ---------- helper ----------

def body_md5(text):

    text = text.strip()

    return hashlib.md5(text.encode()).hexdigest()


def clean_email_body(text: str):

    result = agent.invoke({
        "messages": [
            {"role": "system", "content": PROMPT},
            {"role": "user", "content": text}
        ]
    })

    return result["structured_response"].body_clean

In [58]:
# ---------- загрузим кэш md5 в память ----------

print("Loading cache...")

cached_md5 = set(
    r[0] for r in client.query("""
        SELECT raw_md5
        FROM mailkb.llm_body_clean_cache
    """).result_rows
)

print("Cached bodies:", len(cached_md5))

Loading cache...
Cached bodies: 48

In [52]:
# body = df["body_text"][0]
body = df
cleaned = clean_email_body(body)

In [59]:
cleaned

'Добрый день!\n\nХотел у вас уточнить статус по тм014, когда можно продолжать тестировать с исправлениями?\n\nС уважением, Острик Петр'

In [67]:
# ---------- batch параметры ----------

BATCH = 2

In [68]:
# ---------- основной цикл ----------

while True:

    rows = client.query("""
        SELECT
            id,
            body_text
        FROM mailkb.emails
        WHERE body_text IS NOT NULL
          AND body_text != ''
        LIMIT %(limit)s
    """, {"limit": BATCH}).result_rows

    if not rows:
        print("No rows found")
        break

    insert_batch = []

    for email_id, body in rows:

        md5 = body_md5(body)

        # если уже обработано — пропускаем
        if md5 in cached_md5:
            continue

        start = time.time()

        try:

            cleaned = clean_email_body(body)

            latency = int((time.time() - start) * 1000)

            insert_batch.append({
                "raw_md5": md5,
                "parser_version": "v1",
                "model_name": "deepseek-chat",
                "status": "success",
                "body_clean": cleaned,
                "error": "",
                "tokens_in": 0,
                "tokens_out": 0,
                "latency_ms": latency
            })

            cached_md5.add(md5)

        except Exception as e:

            insert_batch.append({
                "raw_md5": md5,
                "parser_version": "v1",
                "model_name": "deepseek-chat",
                "status": "failed",
                "body_clean": "",
                "error": str(e),
                "tokens_in": 0,
                "tokens_out": 0,
                "latency_ms": 0
            })

        print("Processing:", email_id)

if insert_batch:

    data = [
        [
            row["raw_md5"],
            row["parser_version"],
            row["model_name"],
            row["status"],
            row["body_clean"],
            row["error"],
            row["tokens_in"],
            row["tokens_out"],
            row["latency_ms"]
        ]
        for row in insert_batch
    ]

    client.insert(
        "mailkb.llm_body_clean_cache",
        data,
        column_names=[
            "raw_md5",
            "parser_version",
            "model_name",
            "status",
            "body_clean",
            "error",
            "tokens_in",
            "tokens_out",
            "latency_ms"
        ]
    )

    print("Inserted:", len(data))

KeyboardInterrupt:

### batch model agent
чистим батчами

In [69]:
import hashlib
import time
from clickhouse_connect import get_client
from langchain.agents import create_agent
from pydantic import BaseModel, Field
from typing import List


# ---------- LLM schema (batch) ----------

class CleanItem(BaseModel):
    raw_md5: str = Field(description="MD5 of the original raw body (as provided in the input batch)")
    body_clean: str = Field(description="Cleaned top-level email text without quoted history, headers or signatures")

class CleanBatch(BaseModel):
    items: List[CleanItem]

In [71]:
# ---------- LLM agent ----------

agent = create_agent(
    model="deepseek-chat",
    response_format=CleanBatch
)

PROMPT = """
You clean email bodies.

Task:
For each email body, extract ONLY the new message written by the sender.

Remove:
- quoted history (previous replies/forwards)
- repeated headers like From/Sent/Subject
- signatures, phone blocks, company footers

Return JSON matching the schema.

Important:
- DO NOT invent content.
- Return one item per input email with the same raw_md5.
"""


# ---------- ClickHouse ----------

client = clickhouse_connect.get_client(
    host="84.201.160.255",   # замени на свой хост/адрес
    port=8123,
    username="peter",
    password="1234"
)

# ---------- helpers ----------

def body_md5(text: str) -> str:
    text = (text or "").strip()
    return hashlib.md5(text.encode("utf-8")).hexdigest()


def clean_email_bodies_batch(md5_and_text: List[tuple[str, str]]) -> dict[str, str]:
    """
    md5_and_text: list of (raw_md5, body_text)
    returns: dict raw_md5 -> body_clean
    """

    # Собираем вход в понятном для модели виде
    # (важно: включаем raw_md5, чтобы можно было сопоставить ответы)
    blocks = []
    for md5, body in md5_and_text:
        blocks.append(f"raw_md5: {md5}\nbody:\n{body}")

    user_content = "\n\n---\n\n".join(blocks)

    result = agent.invoke({
        "messages": [
            {"role": "system", "content": PROMPT},
            {"role": "user", "content": user_content}
        ]
    })

    batch_obj: CleanBatch = result["structured_response"]

    # Превращаем в dict для удобства
    out = {}
    for item in batch_obj.items:
        out[item.raw_md5] = item.body_clean

    return out

In [73]:
# ---------- load cache md5 to memory ----------

print("Loading cache...")
cached_md5 = set(r[0] for r in client.query("""
    SELECT raw_md5 FROM mailkb.llm_body_clean_cache
""").result_rows)
print("Cached:", len(cached_md5))

Loading cache...
Cached: 48

In [80]:
# ---------- parameters ----------

FETCH_BATCH = 30      # сколько строк читать из emails за раз
LLM_BATCH = 5         # сколько писем отправлять в один LLM запрос (начни с 5-10)
PARSER_VERSION = "v1"
MODEL_NAME = "deepseek-chat"

In [81]:
# ---------- main loop ----------

while True:
    # Для простоты: берём "какие-то" письма (как в твоём шаге 5),
    # но обязательно добавь ORDER BY rand() на тесте, чтобы не крутиться на одном и том же.
    rows = client.query("""
        SELECT id, body_text
        FROM mailkb.emails
        WHERE body_text IS NOT NULL AND body_text != ''
        ORDER BY rand()
        LIMIT %(limit)s
    """, {"limit": FETCH_BATCH}).result_rows

    if not rows:
        print("No rows found, stop.")
        break

    # Отфильтруем уже обработанные по md5
    to_process = []
    for email_id, body in rows:
        md5 = body_md5(body)
        if md5 in cached_md5:
            continue
        to_process.append((md5, body))

    if not to_process:
        print("All fetched rows already cached; fetching next...")
        continue

    # Разбиваем на пачки для LLM
    for i in range(0, len(to_process), LLM_BATCH):
        chunk = to_process[i:i+LLM_BATCH]

        start = time.time()

        try:
            cleaned_map = clean_email_bodies_batch(chunk)
            latency_ms = int((time.time() - start) * 1000)

            # Подготовим данные для вставки в CH: list of lists + column_names
            data = []
            for raw_md5, _body in chunk:
                body_clean = cleaned_map.get(raw_md5, "")
                status = "success" if body_clean.strip() else "failed"
                error = "" if status == "success" else "empty_clean_result"

                data.append([
                    raw_md5,
                    PARSER_VERSION,
                    MODEL_NAME,
                    status,
                    body_clean,
                    error,
                    0,   # tokens_in (пока 0, потом можно заполнить, если у клиента есть usage)
                    0,   # tokens_out
                    latency_ms
                ])

                cached_md5.add(raw_md5)

            client.insert(
                "mailkb.llm_body_clean_cache",
                data,
                column_names=[
                    "raw_md5",
                    "parser_version",
                    "model_name",
                    "status",
                    "body_clean",
                    "error",
                    "tokens_in",
                    "tokens_out",
                    "latency_ms"
                ]
            )

            print(f"Inserted batch: {len(data)} (latency_ms={latency_ms})")

        except Exception as e:
            # Если пачка упала — не теряем всё: можно записать failed для всех md5 в chunk
            err = str(e)
            data = []
            for raw_md5, _body in chunk:
                data.append([
                    raw_md5,
                    PARSER_VERSION,
                    MODEL_NAME,
                    "failed",
                    "",
                    err,
                    0,
                    0,
                    0
                ])
                cached_md5.add(raw_md5)

            client.insert(
                "mailkb.llm_body_clean_cache",
                data,
                column_names=[
                    "raw_md5",
                    "parser_version",
                    "model_name",
                    "status",
                    "body_clean",
                    "error",
                    "tokens_in",
                    "tokens_out",
                    "latency_ms"
                ]
            )

            print(f"Batch failed, inserted failed rows: {len(data)}; error={err}")

Inserted batch: 5 (latency_ms=50381)
Inserted batch: 5 (latency_ms=25194)
Inserted batch: 5 (latency_ms=31707)
Inserted batch: 5 (latency_ms=21130)
Inserted batch: 5 (latency_ms=34198)
Inserted batch: 5 (latency_ms=17904)
Inserted batch: 5 (latency_ms=53076)
Inserted batch: 5 (latency_ms=27121)
Inserted batch: 5 (latency_ms=24617)
Inserted batch: 5 (latency_ms=22815)
Inserted batch: 5 (latency_ms=23213)
Inserted batch: 3 (latency_ms=28559)
Inserted batch: 5 (latency_ms=42284)
Inserted batch: 5 (latency_ms=49179)
Inserted batch: 5 (latency_ms=18030)
Inserted batch: 5 (latency_ms=18800)
Inserted batch: 5 (latency_ms=36437)
Inserted batch: 5 (latency_ms=40306)
Inserted batch: 5 (latency_ms=52406)
Inserted batch: 5 (latency_ms=16687)
Inserted batch: 5 (latency_ms=60343)
Inserted batch: 5 (latency_ms=20106)
Inserted batch: 5 (latency_ms=22168)
Inserted batch: 2 (latency_ms=27935)
Batch failed, inserted failed rows: 5; error=Error code: 400 - {'error': {'message': "An assistant message with 'tool_calls' must be followed by tool messages responding to each 'tool_call_id'. (insufficient tool messages following tool_calls message)", 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_request_error'}}
Inserted batch: 5 (latency_ms=17579)
Inserted batch: 5 (latency_ms=20977)
Inserted batch: 5 (latency_ms=73593)
Inserted batch: 5 (latency_ms=20018)
Inserted batch: 5 (latency_ms=21093)
Inserted batch: 5 (latency_ms=15667)
Inserted batch: 5 (latency_ms=25490)
Inserted batch: 5 (latency_ms=57995)
Inserted batch: 5 (latency_ms=51083)
Inserted batch: 5 (latency_ms=25414)
Inserted batch: 5 (latency_ms=121845)
Inserted batch: 5 (latency_ms=30050)
Inserted batch: 5 (latency_ms=78557)
Inserted batch: 5 (latency_ms=13274)
Inserted batch: 5 (latency_ms=14973)
Inserted batch: 3 (latency_ms=11850)
Inserted batch: 5 (latency_ms=20658)
Inserted batch: 5 (latency_ms=17762)
Inserted batch: 5 (latency_ms=44379)
Inserted batch: 5 (latency_ms=20425)
Inserted batch: 5 (latency_ms=24911)
Inserted batch: 4 (latency_ms=26400)
Inserted batch: 5 (latency_ms=19452)
Inserted batch: 5 (latency_ms=35090)
Inserted batch: 5 (latency_ms=18356)
Inserted batch: 5 (latency_ms=103751)
Inserted batch: 5 (latency_ms=40219)
Inserted batch: 5 (latency_ms=65420)
Inserted batch: 5 (latency_ms=20125)
Inserted batch: 5 (latency_ms=34723)
Inserted batch: 5 (latency_ms=116320)
Inserted batch: 5 (latency_ms=40354)
Inserted batch: 2 (latency_ms=37489)
Inserted batch: 5 (latency_ms=111632)
Inserted batch: 5 (latency_ms=42495)
Inserted batch: 5 (latency_ms=20907)
Inserted batch: 5 (latency_ms=51687)
Inserted batch: 5 (latency_ms=27723)
Inserted batch: 4 (latency_ms=32025)
Inserted batch: 5 (latency_ms=17215)
Inserted batch: 5 (latency_ms=54286)
Inserted batch: 5 (latency_ms=27681)
Inserted batch: 5 (latency_ms=21309)
Inserted batch: 5 (latency_ms=27536)
Inserted batch: 3 (latency_ms=46113)
Inserted batch: 5 (latency_ms=65795)
Inserted batch: 5 (latency_ms=17678)
Inserted batch: 5 (latency_ms=20661)
Inserted batch: 5 (latency_ms=18755)
Inserted batch: 5 (latency_ms=27572)
Inserted batch: 4 (latency_ms=32268)
Inserted batch: 5 (latency_ms=17408)
Inserted batch: 5 (latency_ms=31525)
Inserted batch: 5 (latency_ms=17314)
Inserted batch: 5 (latency_ms=70832)
Inserted batch: 5 (latency_ms=15917)
Inserted batch: 1 (latency_ms=9012)
Inserted batch: 5 (latency_ms=20987)
Inserted batch: 5 (latency_ms=14636)
Inserted batch: 5 (latency_ms=30672)
Inserted batch: 5 (latency_ms=30231)
Inserted batch: 5 (latency_ms=31744)
Inserted batch: 4 (latency_ms=31924)
Inserted batch: 5 (latency_ms=28059)
Inserted batch: 5 (latency_ms=20162)
Inserted batch: 5 (latency_ms=28960)
Inserted batch: 5 (latency_ms=46908)
Inserted batch: 5 (latency_ms=16771)
Inserted batch: 3 (latency_ms=15112)
Inserted batch: 5 (latency_ms=17650)
Inserted batch: 5 (latency_ms=21394)
Inserted batch: 5 (latency_ms=16586)
Inserted batch: 5 (latency_ms=73693)
Inserted batch: 5 (latency_ms=26051)
Inserted batch: 4 (latency_ms=16903)
Inserted batch: 5 (latency_ms=21963)
Inserted batch: 5 (latency_ms=15708)
Inserted batch: 5 (latency_ms=41828)
Inserted batch: 5 (latency_ms=19829)
Inserted batch: 5 (latency_ms=62591)
Inserted batch: 4 (latency_ms=26732)
Inserted batch: 5 (latency_ms=15164)
Inserted batch: 5 (latency_ms=23164)
Inserted batch: 5 (latency_ms=23495)
Inserted batch: 5 (latency_ms=18657)
Inserted batch: 5 (latency_ms=53380)
Inserted batch: 5 (latency_ms=18928)
Inserted batch: 5 (latency_ms=25965)
Inserted batch: 5 (latency_ms=26941)
Inserted batch: 5 (latency_ms=22771)
Inserted batch: 5 (latency_ms=21596)
Inserted batch: 5 (latency_ms=29402)
Inserted batch: 2 (latency_ms=12998)
Inserted batch: 5 (latency_ms=26468)
Inserted batch: 5 (latency_ms=26071)
Inserted batch: 5 (latency_ms=31932)
Inserted batch: 5 (latency_ms=25534)
Inserted batch: 5 (latency_ms=24871)
Inserted batch: 3 (latency_ms=10591)
Inserted batch: 5 (latency_ms=19261)
Inserted batch: 5 (latency_ms=48742)
Inserted batch: 5 (latency_ms=27434)
Inserted batch: 5 (latency_ms=17629)
Inserted batch: 5 (latency_ms=25824)
Inserted batch: 3 (latency_ms=18748)
Inserted batch: 5 (latency_ms=21875)
Inserted batch: 5 (latency_ms=38929)
Inserted batch: 5 (latency_ms=25745)
Inserted batch: 5 (latency_ms=23491)
Inserted batch: 5 (latency_ms=58329)
Inserted batch: 5 (latency_ms=25947)
Inserted batch: 5 (latency_ms=35913)
Inserted batch: 5 (latency_ms=47164)
Inserted batch: 5 (latency_ms=63305)
Inserted batch: 5 (latency_ms=30367)
Inserted batch: 5 (latency_ms=41444)
Inserted batch: 3 (latency_ms=18523)
Inserted batch: 5 (latency_ms=35326)
Inserted batch: 5 (latency_ms=22194)
Inserted batch: 5 (latency_ms=23679)
Inserted batch: 5 (latency_ms=21255)
Inserted batch: 4 (latency_ms=22231)
Inserted batch: 5 (latency_ms=24063)
Inserted batch: 5 (latency_ms=20382)
Inserted batch: 5 (latency_ms=22608)
Inserted batch: 5 (latency_ms=19705)
Inserted batch: 5 (latency_ms=27082)
Inserted batch: 4 (latency_ms=12032)

KeyboardInterrupt:

### вложенный класс

In [83]:
import pandas as pd
import clickhouse_connect
from datetime import datetime
import os
from dotenv import load_dotenv

load_dotenv()

True

In [84]:

# создаём клиент
# client = clickhouse_connect.get_client(
#     host= os.getenv("CLICKHOUSE_HOST") ,   # замени на свой хост/адрес
#     port= os.getenv("CLICKHOUSE_PORT"),
#     username=  os.getenv("CLICKHOUSE_USER"),
#     password= os.getenv("CLICKHOUSE_PASSWORD")
# )
client = clickhouse_connect.get_client(
    host="84.201.160.255",   # замени на свой хост/адрес
    port=8123,
    username="peter",
    password="1234"
)

In [90]:
# SQL-запрос
query = "SELECT * FROM mailkb.emails ORDER BY id DESC LIMIT 5"

# вернуть сразу DataFrame
df = client.query_df(query)

In [91]:
# df = df.iloc[2]['body_text']

In [92]:
df

,id,message_id,subject,from_addr,to_addr,cc_addr,bcc_addr,sent_at_utc,sent_at_raw,folder,body_text,body_html,subject_norm,thread_id
0,jxQhgOJ7J0GmAtuWNDdmMQAAANUzoWuqRNoH9-5MgJqWgq...,jxQhgOJ7J0GmAtuWNDdmMQAAANUzoWuqRNoH9-5MgJqWgq...,"RE: Запуск SAP: 6 Филиалов, график координаци...",[Maxim.Lyutov@ru.ey.com],"[Ilya.Sergeev@ru.ey.com, anton.chigvintsev@bea...",[],[],2018-08-19 11:48:48,"Sun, 19 Aug 2018 11:48:48 +0000",unknown,Это МТЗ?\r\n________________________________\r...,"<html><head>\r\n<meta http-equiv=""Content-Type...","Запуск sap: 6 Филиалов, график координации пе...",d314be6c1694dcc877bf114422956bba
1,jxQhgOJ7J0GmAtuWNDdmMQAAANUzoWuqRNoH9-5MgJqWgq...,jxQhgOJ7J0GmAtuWNDdmMQAAANUzoWuqRNoH9-5MgJqWgq...,"RE: Запуск SAP: 6 Филиалов, график координаци...",[Maxim.Lyutov@ru.ey.com],"[anton.chigvintsev@bearingpoint.ru, ce-rustam....",[],[],2018-08-19 12:54:33,"Sun, 19 Aug 2018 12:54:33 +0000",unknown,"Илья, Антн,\r\nдобавьте статус гашения Всд в д...","<html><head>\r\n<meta http-equiv=""Content-Type...","Запуск sap: 6 Филиалов, график координации пе...",d314be6c1694dcc877bf114422956bba
2,jxQhgOJ7J0GmAtuWNDdmMQAAANUzoWuqRNoH9-5MgJqWgq...,jxQhgOJ7J0GmAtuWNDdmMQAAANUzoWuqRNoH9-5MgJqWgq...,"RE: Запуск SAP: 6 Филиалов, график координаци...",[Maxim.Lyutov@ru.ey.com],"[anton.chigvintsev@bearingpoint.ru, ce-yuriy.k...",[],[],2018-08-19 11:38:13,"Sun, 19 Aug 2018 11:38:13 +0000",unknown,"Илья Сергеев, проверь пожалуйста наличие всд в...","<html><head>\r\n<meta http-equiv=""Content-Type...","Запуск sap: 6 Филиалов, график координации пе...",d314be6c1694dcc877bf114422956bba
3,archive.pst::3027620,,,[],[],[],[],1970-01-01 00:00:00,,unknown,szeligowska_ea@segezha-group.com 16:27: \r\nПё...,"<html xmlns=""http://schemas.microsoft.com/2008...",no_subject,7c4b5aaa31326e5523268cd24c3466cf
4,archive.pst::3024932,,,[],[],[],[],1970-01-01 00:00:00,,unknown,Пропущенный звонок конференц-связи от пользова...,"<html xmlns=""http://schemas.microsoft.com/2008...",no_subject,7c4b5aaa31326e5523268cd24c3466cf

#### вариант 1

In [99]:
## импортируем либы для структурированного ответа

from pydantic import BaseModel, Field
from langchain.agents import create_agent
from typing import List



class MailInfo(BaseModel):
    """Contact information for a person."""
    topic: str = Field(..., description="The name of the mail ")
    email_body: str = Field(..., description="The email clean body text")
    date: str = Field(..., description="The date and time the message was sent. Format: YYYY-MM-DD")
    mail_query_number: int = Field(..., description="The mail query in topic number")
    key_words

class MailChainInfo(BaseModel):
    emails: List[MailInfo] = Field(description='mail chain info')
    #темы

agent = create_agent(
    model="",
    response_format=MailChainInfo  # Auto-selects ProviderStrategy
)

# result = agent.invoke({
#     "messages": [{"role": "user", "content": "Extract contact info from: {}"}]
# })
#
# print(result["structured_response"])
# ContactInfo(name='John Doe', email='john@example.com', phone='(555) 123-4567')

In [97]:
df['body_text'][0]

'Это МТЗ?\r\n________________________________\r\n\r\nОт: Ilya M Sergeev <Ilya.Sergeev@ru.ey.com>\r\nОтправлено: воскресенье, 19 августа 2018 г. 14:47\r\nКому: Maxim P Lyutov <Maxim.Lyutov@ru.ey.com>,Chigvintsev Anton <anton.chigvintsev@bearingpoint.ru>,"Kozlov Yuriy(CE)" <ce-yuriy.kozlov@bearingpoint.ru>,Алексей Алмакаев <A.Almakaev@agrohold.ru>,Zhanna L Vakhrusheva <Zhanna.L.Vakhrusheva@ru.ey.com>,Алексей Филимончук <A.Filimonchuk@agrohold.ru>,Андрей Кравченко <A.Kravchenko@agrohold.ru>,Андрей Николаевич Петров <A.N.Petrov@agrohold.ru>,Yuri A Denisov <Yuri.Denisov@ru.ey.com>,Dmitry V Karpov <Dmitry.Karpov@ru.ey.com>,Alexey S Fedoseev <Alexey.Fedoseev@ru.ey.com>,Валерий Бражников <V.Brazhnikov@agrohold.ru>,Vadim Kotenko <V.Kotenko@agrohold.ru>,"Scherbakov Andrey(CE)" <ce-andrey.scherbakov@bearingpoint.ru>,Андрей Владимирович Самойленко <AV.Samoylenko@agrohold.ru>,Вадим Просолупов <V.Prosolupov@agrohold.ru>,Александр Игоревич Александров <a.i.aleksandrov@agrohold.ru>,Иван Лосев <I.Losev@agrohold.ru>,Александр Пчелин <A.Pchelin@agrohold.ru>,Карина Кувшинова <K.Kuvshinova@agrohold.ru>,Екатерина Кармишина <E.Khamina@agrohold.ru>,Дмитрий Зинков <D.Zinkov@agrohold.ru>,Александра Горелова <A.Gorelova@agrohold.ru>,WG Sklad 21 <sklad-rst@agrohold.ru>,Владимир Викторович Скворцов <vv.skvortsov@agrohold.ru>,Надежда Иванова <ivanova@agrohold.ru>,Олеся Любакова <Zakurdaeva@agrohold.ru>,Сергей Лынов <S.Lynov@agrohold.ru>,Денис Леонидович Олейник <dl.oleynik@agrohold.ru>,Алексей Потапов <A.M.Potapov@agrohold.ru>,Денис Кисарин <D.Kisarin@agrohold.ru>,Ренат Халилюлин <Halilulin@agrohold.ru>,Дмитрий Топоров <D.Toporov@agrohold.ru>,Владимир Лавейкин <V.Laveykin@agrohold.ru>,Павел Прокашев <P.Prokashev@agrohold.ru>,Егор Смирнов <E.Smirnov@agrohold.ru>,Екатерина Евгеньевна Полякова <E.E.Polyakova@agrohold.ru>,Павел Шабанов <P.Shabanov@agrohold.ru>,Анна Себелева <A.Sebeleva@agrohold.ru>,Василий Соляник <V.Solyanik@agrohold.ru>,Алексей Вадимович Алексеев <A.Alexeyev@agrohold.ru>,Ivan S Butyagin <ivan.butyagin@ru.ey.com>,Anna V Turygina <Anna.Turygina@ru.ey.com>,Evgeny L Kuznetsov <Evgeny.Kuznetsov@ru.ey.com>,Alexander S Larin <Alexander.Larin@ru.ey.com>,Igor M Trifonov <Igor.Trifonov@ru.ey.com>,Nikita A Savkin <nikita.savkin@ru.ey.com>,Sergey Popov <popov.sergey@bearingpoint.ru>,Artem I Krasnoperov <Artem.Krasnoperov@ru.ey.com>,Александр Жуков <alexander.zhukov@solmix.spb.ru>,Egorova Tatiana <tatiana.egorova@bearingpoint.ru>,Tkachenko Sergey <sergey.tkachenko@bearingpoint.ru>,"Zhukov Alexander(CE)" <ce-alexander.zhukov@bearingpoint.ru>,Анна Найда <A.Naida@agrohold.ru>,Павел Болотников <P.Bolotnikov@agrohold.ru>,Евгения Владимировна Гончарова <E.V.Goncharova@agrohold.ru>,Наталья Межина <N.Megina@agrohold.ru>,Альбина Беспарточная <a.bespartochnaya@agrohold.ru>,Анна Клименкова <A.Klimenkova@agrohold.ru>,Дарья Юркевич <D.Yurkevich@agrohold.ru>,Екатерина Еременко <E.Yeremenko@agrohold.ru>,Светлана Смывина <Kshnaikina@agrohold.ru>,Анна Извекова <a.izvekova@agrohold.ru>,Максим Лимов <M.Limov@agrohold.ru>,Ксения Боброва <k.bobrova@agrohold.ru>,Khadzhieva Kristina <kristina.khadzhieva@bearingpoint.ru>,Bektur Kazakbaev <Bektur.Kazakbaev@ru.ey.com>,Zyryanova Nadezhda <nadezhda.zyryanova@bearingpoint.ru>,Kosmynin Egor <egor.kosmynin@bearingpoint.ru>,"Batyrshin Rustam(CE)" <ce-rustam.batyrshin@bearingpoint.ru>,Levanovich Vladislav <vladislav.levanovich@bearingpoint.ru>,Makarenko Aleksei <aleksei.makarenko@bearingpoint.ru>,Krashchenko Oleg <oleg.krashchenko@bearingpoint.ru>,Aleksandr V Muravev <Aleksandr.Muravev@ru.ey.com>,Viacheslav A Polukhin <Viacheslav.Polukhin@ru.ey.com>,Dmitry I Zhulev <Dmitry.Zhulev@ru.ey.com>,David V Zakarian <David.Zakarian@ru.ey.com>,Dimitriy Karpov <dimitriy.karpov@gmail.com>,Petr S Lobach <Petr.Lobach@ru.ey.com>,Liana R Sadykova <Liana.Sadykova@ru.ey.com>,Dondukov Ivan <ivan.dondukov@bearingpoint.ru>,Balyabina Anna <anna.balyabina@bearingpoint.ru>,Fayzullaeva Sabina <sabina.fayzullaeva@bearingpoint.ru>,Isaev Yury <yury.isaev@bearingpoint.ru>,Timoshin Andrey <andrey.timoshin@bearingpoint.ru>,Ostrik Petr <petr.ostrik@bearingpoint.ru>,Te Alexandr <alexandr.te@bearingpoint.ru>,Artem V Rasstanaev <Artem.Rasstanaev@ru.ey.com>,Fedor B Ermolaev <Fedor.Ermolaev@ru.ey.com>,Stanislav E Cherkassky <Stanislav.Cherkassky@ru.ey.com>,Alsu R Golubyatnikova <Alsu.Fatykhova@ru.ey.com>,Mikhail V Vasilov <Mikhail.Vasilov@ru.ey.com>,Nikita S Galiarda <Nikita.Galiarda@ru.ey.com>,Elmira A Ufimskaia <Elmira.Ufimskaia@ru.ey.com>,Vladislav E Kutka <Vladislav.Kutka@ru.ey.com>,Stanislav S Solovyanenko <Stanislav.Solovyanenko@ru.ey.com>,Petr S Sharygin <Petr.Sharygin@ru.ey.com>,"Prusov Mikhail (CE)" <ce-mikhail.prusov@bearingpoint.ru>\r\nТема: RE: Запуск SAP: 6 Филиалов, график координации перехода\r\n\r\n\r\n\r\n\r\nНет по 35-ти позициям по поставкам:\r\n\r\n1800010786\r\n\r\n1800010771\r\n\r\n1800010774\r\n\r\n1800010778\r\n\r\n1800010791\r\n\r\n \r\n\r\nС уважением,\r\n\r\n\r\n\r\nИлья Сергеев | Группа «Интеграция с ФГИС Меркурий» |\r\n\r\nПроект «Эволюция бизнеса»\r\n\r\ne-mail: Ilya.Sergeev@ru.ey.com <mailto:Ilya.Sergeev@ru.ey.com> \r\n\r\nмоб. +7-967-129-92-98\r\n\r\n \r\n\r\n \r\n\r\nFrom: Maxim P Lyutov \r\nSent: Sunday, August 19, 2018 2:38 PM\r\nTo: Chigvintsev Anton <anton.chigvintsev@bearingpoint.ru>; Kozlov Yuriy(CE) <ce-yuriy.kozlov@bearingpoint.ru>; Алексей Алмакаев <A.Almakaev@agrohold.ru>; Zhanna L Vakhrusheva <Zhanna.L.Vakhrusheva@ru.ey.com>; Алексей Филимончук <A.Filimonchuk@agrohold.ru>; Андрей Кравченко <A.Kravchenko@agrohold.ru>; Андрей Николаевич Петров <A.N.Petrov@agrohold.ru>; Yuri A Denisov <Yuri.Denisov@ru.ey.com>; Dmitry V Karpov <Dmitry.Karpov@ru.ey.com>; Alexey S Fedoseev <Alexey.Fedoseev@ru.ey.com>; Валерий Бражников <V.Brazhnikov@agrohold.ru>; Vadim Kotenko <V.Kotenko@agrohold.ru>; Scherbakov Andrey(CE) <ce-andrey.scherbakov@bearingpoint.ru>; Андрей Владимирович Самойленко <AV.Samoylenko@agrohold.ru>; Вадим Просолупов <V.Prosolupov@agrohold.ru>; Александр Игоревич Александров <a.i.aleksandrov@agrohold.ru>; Иван Лосев <I.Losev@agrohold.ru>; Александр Пчелин <A.Pchelin@agrohold.ru>; Карина Кувшинова <K.Kuvshinova@agrohold.ru>; Екатерина Кармишина <E.Khamina@agrohold.ru>; Дмитрий Зинков <D.Zinkov@agrohold.ru>; Александра Горелова <A.Gorelova@agrohold.ru>; WG Sklad 21 <sklad-rst@agrohold.ru>; Владимир Викторович Скворцов <vv.skvortsov@agrohold.ru>; Надежда Иванова <ivanova@agrohold.ru>; Олеся Любакова <Zakurdaeva@agrohold.ru>; Сергей Лынов <S.Lynov@agrohold.ru>; Денис Леонидович Олейник <dl.oleynik@agrohold.ru>; Алексей Потапов <A.M.Potapov@agrohold.ru>; Денис Кисарин <D.Kisarin@agrohold.ru>; Ренат Халилюлин <Halilulin@agrohold.ru>; Дмитрий Топоров <D.Toporov@agrohold.ru>; Владимир Лавейкин <V.Laveykin@agrohold.ru>; Павел Прокашев <P.Prokashev@agrohold.ru>; Егор Смирнов <E.Smirnov@agrohold.ru>; Екатерина Евгеньевна Полякова <E.E.Polyakova@agrohold.ru>; Павел Шабанов <P.Shabanov@agrohold.ru>; Анна Себелева <A.Sebeleva@agrohold.ru>; Василий Соляник <V.Solyanik@agrohold.ru>; Алексей Вадимович Алексеев <A.Alexeyev@agrohold.ru>; Ivan S Butyagin <ivan.butyagin@ru.ey.com>; Anna V Turygina <Anna.Turygina@ru.ey.com>; Evgeny L Kuznetsov <Evgeny.Kuznetsov@ru.ey.com>; Alexander S Larin <Alexander.Larin@ru.ey.com>; Igor M Trifonov <Igor.Trifonov@ru.ey.com>; Nikita A Savkin <nikita.savkin@ru.ey.com>; Sergey Popov <popov.sergey@bearingpoint.ru>; Artem I Krasnoperov <Artem.Krasnoperov@ru.ey.com>; Александр Жуков <alexander.zhukov@solmix.spb.ru>; Egorova Tatiana <tatiana.egorova@bearingpoint.ru>; Tkachenko Sergey <sergey.tkachenko@bearingpoint.ru>; Zhukov Alexander(CE) <ce-alexander.zhukov@bearingpoint.ru>; Анна Найда <A.Naida@agrohold.ru>; Павел Болотников <P.Bolotnikov@agrohold.ru>; Евгения Владимировна Гончарова <E.V.Goncharova@agrohold.ru>; Наталья Межина <N.Megina@agrohold.ru>; Альбина Беспарточная <a.bespartochnaya@agrohold.ru>; Анна Клименкова <A.Klimenkova@agrohold.ru>; Дарья Юркевич <D.Yurkevich@agrohold.ru>; Екатерина Еременко <E.Yeremenko@agrohold.ru>; Светлана Смывина <Kshnaikina@agrohold.ru>; Анна Извекова <a.izvekova@agrohold.ru>; Максим Лимов <M.Limov@agrohold.ru>; Ксения Боброва <k.bobrova@agrohold.ru>; Ilya M Sergeev <Ilya.Sergeev@ru.ey.com>; Khadzhieva Kristina <kristina.khadzhieva@bearingpoint.ru>; Bektur Kazakbaev <Bektur.Kazakbaev@ru.ey.com>; Zyryanova Nadezhda <nadezhda.zyryanova@bearingpoint.ru>; Kosmynin Egor <egor.kosmynin@bearingpoint.ru>; Batyrshin Rustam(CE) <ce-rustam.batyrshin@bearingpoint.ru>; Levanovich Vladislav <vladislav.levanovich@bearingpoint.ru>; Makarenko Aleksei <aleksei.makarenko@bearingpoint.ru>; Krashchenko Oleg <oleg.krashchenko@bearingpoint.ru>; Aleksandr V Muravev <Aleksandr.Muravev@ru.ey.com>; Viacheslav A Polukhin <Viacheslav.Polukhin@ru.ey.com>; Dmitry I Zhulev <Dmitry.Zhulev@ru.ey.com>; David V Zakarian <David.Zakarian@ru.ey.com>; Dimitriy Karpov <dimitriy.karpov@gmail.com>; Petr S Lobach <Petr.Lobach@ru.ey.com>; Liana R Sadykova <Liana.Sadykova@ru.ey.com>; Dondukov Ivan <ivan.dondukov@bearingpoint.ru>; Balyabina Anna <anna.balyabina@bearingpoint.ru>; Fayzullaeva Sabina <sabina.fayzullaeva@bearingpoint.ru>; Isaev Yury <yury.isaev@bearingpoint.ru>; Timoshin Andrey <andrey.timoshin@bearingpoint.ru>; Ostrik Petr <petr.ostrik@bearingpoint.ru>; Te Alexandr <alexandr.te@bearingpoint.ru>; Artem V Rasstanaev <Artem.Rasstanaev@ru.ey.com>; Fedor B Ermolaev <Fedor.Ermolaev@ru.ey.com>; Stanislav E Cherkassky <Stanislav.Cherkassky@ru.ey.com>; Alsu R Golubyatnikova <Alsu.Fatykhova@ru.ey.com>; Mikhail V Vasilov <Mikhail.Vasilov@ru.ey.com>; Nikita S Galiarda <Nikita.Galiarda@ru.ey.com>; Elmira A Ufimskaia <Elmira.Ufimskaia@ru.ey.com>; Vladislav E Kutka <Vladislav.Kutka@ru.ey.com>; Stanislav S Solovyanenko <Stanislav.Solovyanenko@ru.ey.com>; Petr S Sharygin <Petr.Sharygin@ru.ey.com>; Prusov Mikhail (CE) <ce-mikhail.prusov@bearingpoint.ru>\r\nSubject: RE: Запуск SAP: 6 Филиалов, график координации перехода\r\n\r\n \r\n\r\nИлья Сергеев, проверь пожалуйста наличие всд во всех поставках.\r\n\r\n________________________________\r\n\r\nОт: Chigvintsev Anton <anton.chigvintsev@bearingpoint.ru <mailto:anton.chigvintsev@bearingpoint.ru> >\r\nОтправлено: воскресенье, 19 августа 2018 г. 14:12\r\nКому: "Kozlov Yuriy(CE)" <ce-yuriy.kozlov@bearingpoint.ru <mailto:ce-yuriy.kozlov@bearingpoint.ru> >,Алексей Алмакаев <A.Almakaev@agrohold.ru <mailto:A.Almakaev@agrohold.ru> >,Zhanna L Vakhrusheva <Zhanna.L.Vakhrusheva@ru.ey.com <mailto:Zhanna.L.Vakhrusheva@ru.ey.com> >,Алексей Филимончук <A.Filimonchuk@agrohold.ru <mailto:A.Filimonchuk@agrohold.ru> >,Андрей Кравченко <A.Kravchenko@agrohold.ru <mailto:A.Kravchenko@agrohold.ru> >,Андрей Николаевич Петров <A.N.Petrov@agrohold.ru <mailto:A.N.Petrov@agrohold.ru> >,Yuri A Denisov <Yuri.Denisov@ru.ey.com <mailto:Yuri.Denisov@ru.ey.com> >,Dmitry V Karpov <Dmitry.Karpov@ru.ey.com <mailto:Dmitry.Karpov@ru.ey.com> >,Alexey S Fedoseev <Alexey.Fedoseev@ru.ey.com <mailto:Alexey.Fedoseev@ru.ey.com> >,Валерий Бражников <V.Brazhnikov@agrohold.ru <mailto:V.Brazhnikov@agrohold.ru> >,Vadim Kotenko <V.Kotenko@agrohold.ru <mailto:V.Kotenko@agrohold.ru> >,"Scherbakov Andrey(CE)" <ce-andrey.scherbakov@bearingpoint.ru <mailto:ce-andrey.scherbakov@bearingpoint.ru> >,Андрей Владимирович Самойленко <AV.Samoylenko@agrohold.ru <mailto:AV.Samoylenko@agrohold.ru> >,Вадим Просолупов <V.Prosolupov@agrohold.ru <mailto:V.Prosolupov@agrohold.ru> >,Александр Игоревич Александров <a.i.aleksandrov@agrohold.ru <mailto:a.i.aleksandrov@agrohold.ru> >,Иван Лосев <I.Losev@agrohold.ru <mailto:I.Losev@agrohold.ru> >,Александр Пчелин <A.Pchelin@agrohold.ru <mailto:A.Pchelin@agrohold.ru> >,Карина Кувшинова <K.Kuvshinova@agrohold.ru <mailto:K.Kuvshinova@agrohold.ru> >,Екатерина Кармишина <E.Khamina@agrohold.ru <mailto:E.Khamina@agrohold.ru> >,Дмитрий Зинков <D.Zinkov@agrohold.ru <mailto:D.Zinkov@agrohold.ru> >,Александра Горелова <A.Gorelova@agrohold.ru <mailto:A.Gorelova@agrohold.ru> >,WG Sklad 21 <sklad-rst@agrohold.ru <mailto:sklad-rst@agrohold.ru> >,Владимир Викторович Скворцов <vv.skvortsov@agrohold.ru <mailto:vv.skvortsov@agrohold.ru> >,Надежда Иванова <ivanova@agrohold.ru <mailto:ivanova@agrohold.ru> >,Олеся Любакова <Zakurdaeva@agrohold.ru <mailto:Zakurdaeva@agrohold.ru> >,Сергей Лынов <S.Lynov@agrohold.ru <mailto:S.Lynov@agrohold.ru> >,Денис Леонидович Олейник <dl.oleynik@agrohold.ru <mailto:dl.oleynik@agrohold.ru> >,Алексей Потапов <A.M.Potapov@agrohold.ru <mailto:A.M.Potapov@agrohold.ru> >,Денис Кисарин <D.Kisarin@agrohold.ru <mailto:D.Kisarin@agrohold.ru> >,Ренат Халилюлин <Halilulin@agrohold.ru <mailto:Halilulin@agrohold.ru> >,Дмитрий Топоров <D.Toporov@agrohold.ru <mailto:D.Toporov@agrohold.ru> >,Владимир Лавейкин <V.Laveykin@agrohold.ru <mailto:V.Laveykin@agrohold.ru> >,Павел Прокашев <P.Prokashev@agrohold.ru <mailto:P.Prokashev@agrohold.ru> >,Егор Смирнов <E.Smirnov@agrohold.ru <mailto:E.Smirnov@agrohold.ru> >,Екатерина Евгеньевна Полякова <E.E.Polyakova@agrohold.ru <mailto:E.E.Polyakova@agrohold.ru> >,Павел Шабанов <P.Shabanov@agrohold.ru <mailto:P.Shabanov@agrohold.ru> >,Анна Себелева <A.Sebeleva@agrohold.ru <mailto:A.Sebeleva@agrohold.ru> >,Василий Соляник <V.Solyanik@agrohold.ru <mailto:V.Solyanik@agrohold.ru> >,Алексей Вадимович Алексеев <A.Alexeyev@agrohold.ru <mailto:A.Alexeyev@agrohold.ru> >,Ivan S Butyagin <ivan.butyagin@ru.ey.com <mailto:ivan.butyagin@ru.ey.com> >,Anna V Turygina <Anna.Turygina@ru.ey.com <mailto:Anna.Turygina@ru.ey.com> >,Evgeny L Kuznetsov <Evgeny.Kuznetsov@ru.ey.com <mailto:Evgeny.Kuznetsov@ru.ey.com> >,Alexander S Larin <Alexander.Larin@ru.ey.com <mailto:Alexander.Larin@ru.ey.com> >,Igor M Trifonov <Igor.Trifonov@ru.ey.com <mailto:Igor.Trifonov@ru.ey.com> >,Nikita A Savkin <nikita.savkin@ru.ey.com <mailto:nikita.savkin@ru.ey.com> >,Sergey Popov <popov.sergey@bearingpoint.ru <mailto:popov.sergey@bearingpoint.ru> >,Artem I Krasnoperov <Artem.Krasnoperov@ru.ey.com <mailto:Artem.Krasnoperov@ru.ey.com> >,Александр Жуков <alexander.zhukov@solmix.spb.ru <mailto:alexander.zhukov@solmix.spb.ru> >,Egorova Tatiana <tatiana.egorova@bearingpoint.ru <mailto:tatiana.egorova@bearingpoint.ru> >,Tkachenko Sergey <sergey.tkachenko@bearingpoint.ru <mailto:sergey.tkachenko@bearingpoint.ru> >,Maxim P Lyutov <Maxim.Lyutov@ru.ey.com <mailto:Maxim.Lyutov@ru.ey.com> >,"Zhukov Alexander(CE)" <ce-alexander.zhukov@bearingpoint.ru <mailto:ce-alexander.zhukov@bearingpoint.ru> >,Анна Найда <A.Naida@agrohold.ru <mailto:A.Naida@agrohold.ru> >,Павел Болотников <P.Bolotnikov@agrohold.ru <mailto:P.Bolotnikov@agrohold.ru> >,Евгения Владимировна Гончарова <E.V.Goncharova@agrohold.ru <mailto:E.V.Goncharova@agrohold.ru> >,Наталья Межина <N.Megina@agrohold.ru <mailto:N.Megina@agrohold.ru> >,Альбина Беспарточная <a.bespartochnaya@agrohold.ru <mailto:a.bespartochnaya@agrohold.ru> >,Анна Клименкова <A.Klimenkova@agrohold.ru <mailto:A.Klimenkova@agrohold.ru> >,Дарья Юркевич <D.Yurkevich@agrohold.ru <mailto:D.Yurkevich@agrohold.ru> >,Екатерина Еременко <E.Yeremenko@agrohold.ru <mailto:E.Yeremenko@agrohold.ru> >,Денис Леонидович Олейник <dl.oleynik@agrohold.ru <mailto:dl.oleynik@agrohold.ru> >,Сергей Лынов <S.Lynov@agrohold.ru <mailto:S.Lynov@agrohold.ru> >,Денис Кисарин <D.Kisarin@agrohold.ru <mailto:D.Kisarin@agrohold.ru> >,Алексей Потапов <A.M.Potapov@agrohold.ru <mailto:A.M.Potapov@agrohold.ru> >,Светлана Смывина <Kshnaikina@agrohold.ru <mailto:Kshnaikina@agrohold.ru> >,Олеся Любакова <Zakurdaeva@agrohold.ru <mailto:Zakurdaeva@agrohold.ru> >,Екатерина Кармишина <E.Khamina@agrohold.ru <mailto:E.Khamina@agrohold.ru> >,Анна Извекова <a.izvekova@agrohold.ru <mailto:a.izvekova@agrohold.ru> >,Максим Лимов <M.Limov@agrohold.ru <mailto:M.Limov@agrohold.ru> >,Павел Шабанов <P.Shabanov@agrohold.ru <mailto:P.Shabanov@agrohold.ru> >,Егор Смирнов <E.Smirnov@agrohold.ru <mailto:E.Smirnov@agrohold.ru> >,Ксения Боброва <k.bobrova@agrohold.ru <mailto:k.bobrova@agrohold.ru> >,Анна Себелева <A.Sebeleva@agrohold.ru <mailto:A.Sebeleva@agrohold.ru> >,Василий Соляник <V.Solyanik@agrohold.ru <mailto:V.Solyanik@agrohold.ru> >,Ilya M Sergeev <Ilya.Sergeev@ru.ey.com <mailto:Ilya.Sergeev@ru.ey.com> >,Khadzhieva Kristina <kristina.khadzhieva@bearingpoint.ru <mailto:kristina.khadzhieva@bearingpoint.ru> >,Bektur Kazakbaev <Bektur.Kazakbaev@ru.ey.com <mailto:Bektur.Kazakbaev@ru.ey.com> >,Zyryanova Nadezhda <nadezhda.zyryanova@bearingpoint.ru <mailto:nadezhda.zyryanova@bearingpoint.ru> >,Kosmynin Egor <egor.kosmynin@bearingpoint.ru <mailto:egor.kosmynin@bearingpoint.ru> >,"Batyrshin Rustam(CE)" <ce-rustam.batyrshin@bearingpoint.ru <mailto:ce-rustam.batyrshin@bearingpoint.ru> >,Levanovich Vladislav <vladislav.levanovich@bearingpoint.ru <mailto:vladislav.levanovich@bearingpoint.ru> >,Makarenko Aleksei <aleksei.makarenko@bearingpoint.ru <mailto:aleksei.makarenko@bearingpoint.ru> >,Krashchenko Oleg <oleg.krashchenko@bearingpoint.ru <mailto:oleg.krashchenko@bearingpoint.ru> >,Aleksandr V Muravev <Aleksandr.Muravev@ru.ey.com <mailto:Aleksandr.Muravev@ru.ey.com> >,Alexander S Larin <Alexander.Larin@ru.ey.com <mailto:Alexander.Larin@ru.ey.com> >,Viacheslav A Polukhin <Viacheslav.Polukhin@ru.ey.com <mailto:Viacheslav.Polukhin@ru.ey.com> >,Dmitry I Zhulev <Dmitry.Zhulev@ru.ey.com <mailto:Dmitry.Zhulev@ru.ey.com> >,Igor M Trifonov <Igor.Trifonov@ru.ey.com <mailto:Igor.Trifonov@ru.ey.com> >,David V Zakarian <David.Zakarian@ru.ey.com <mailto:David.Zakarian@ru.ey.com> >,Dimitriy Karpov <dimitriy.karpov@gmail.com <mailto:dimitriy.karpov@gmail.com> >,Petr S Lobach <Petr.Lobach@ru.ey.com <mailto:Petr.Lobach@ru.ey.com> >,Liana R Sadykova <Liana.Sadykova@ru.ey.com <mailto:Liana.Sadykova@ru.ey.com> >,Dondukov Ivan <ivan.dondukov@bearingpoint.ru <mailto:ivan.dondukov@bearingpoint.ru> >,Balyabina Anna <anna.balyabina@bearingpoint.ru <mailto:anna.balyabina@bearingpoint.ru> >,Egorova Tatiana <tatiana.egorova@bearingpoint.ru <mailto:tatiana.egorova@bearingpoint.ru> >,"Zhukov Alexander(CE)" <ce-alexander.zhukov@bearingpoint.ru <mailto:ce-alexander.zhukov@bearingpoint.ru> >,Fayzullaeva Sabina <sabina.fayzullaeva@bearingpoint.ru <mailto:sabina.fayzullaeva@bearingpoint.ru> >,Dondukov Ivan <ivan.dondukov@bearingpoint.ru <mailto:ivan.dondukov@bearingpoint.ru> >,Balyabina Anna <anna.balyabina@bearingpoint.ru <mailto:anna.balyabina@bearingpoint.ru> >,Egorova Tatiana <tatiana.egorova@bearingpoint.ru <mailto:tatiana.egorova@bearingpoint.ru> >,"Zhukov Alexander(CE)" <ce-alexander.zhukov@bearingpoint.ru <mailto:ce-alexander.zhukov@bearingpoint.ru> >,Fayzullaeva Sabina <sabina.fayzullaeva@bearingpoint.ru <mailto:sabina.fayzullaeva@bearingpoint.ru> >,Dondukov Ivan <ivan.dondukov@bearingpoint.ru <mailto:ivan.dondukov@bearingpoint.ru> >,Balyabina Anna <anna.balyabina@bearingpoint.ru <mailto:anna.balyabina@bearingpoint.ru> >,Egorova Tatiana <tatiana.egorova@bearingpoint.ru <mailto:tatiana.egorova@bearingpoint.ru> >,"Zhukov Alexander(CE)" <ce-alexander.zhukov@bearingpoint.ru <mailto:ce-alexander.zhukov@bearingpoint.ru> >,Isaev Yury <yury.isaev@bearingpoint.ru <mailto:yury.isaev@bearingpoint.ru> >,Dondukov Ivan <ivan.dondukov@bearingpoint.ru <mailto:ivan.dondukov@bearingpoint.ru> >,Balyabina Anna <anna.balyabina@bearingpoint.ru <mailto:anna.balyabina@bearingpoint.ru> >,Egorova Tatiana <tatiana.egorova@bearingpoint.ru <mailto:tatiana.egorova@bearingpoint.ru> >,"Zhukov Alexander(CE)" <ce-alexander.zhukov@bearingpoint.ru <mailto:ce-alexander.zhukov@bearingpoint.ru> >,Isaev Yury <yury.isaev@bearingpoint.ru <mailto:yury.isaev@bearingpoint.ru> >,Timoshin Andrey <andrey.timoshin@bearingpoint.ru <mailto:andrey.timoshin@bearingpoint.ru> >,Ostrik Petr <petr.ostrik@bearingpoint.ru <mailto:petr.ostrik@bearingpoint.ru> >,Isaev Yury <yury.isaev@bearingpoint.ru <mailto:yury.isaev@bearingpoint.ru> >,Te Alexandr <alexandr.te@bearingpoint.ru <mailto:alexandr.te@bearingpoint.ru> >,Evgeny L Kuznetsov <Evgeny.Kuznetsov@ru.ey.com <mailto:Evgeny.Kuznetsov@ru.ey.com> >,Krashchenko Oleg <oleg.krashchenko@bearingpoint.ru <mailto:oleg.krashchenko@bearingpoint.ru> >,"Batyrshin Rustam(CE)" <ce-rustam.batyrshin@bearingpoint.ru 

In [98]:
result = agent.invoke({
    "messages": [
        {
            "role": "user",
            "content": f"""Начни обработку строки и вытащи темы писем и email адреса:

{df['body_text'][0]}   """

        }
    ]
})

report = result["messages"][-1].content
print(report)

StructuredOutputValidationError: Failed to parse structured output for tool 'MailChainInfo': Failed to parse data to MailChainInfo: 3 validation errors for MailChainInfo
emails.0.date
  Input should be a valid datetime or date, input is too short [type=datetime_from_date_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.12/v/datetime_from_date_parsing
emails.1.date
  Input should be a valid datetime or date, input is too short [type=datetime_from_date_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.12/v/datetime_from_date_parsing
emails.2.date
  Input should be a valid datetime or date, input is too short [type=datetime_from_date_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.12/v/datetime_from_date_parsing.

#### вариант 2 (12.03.26 -работает)

In [4]:

from pydantic import BaseModel, Field
from typing import List
from langchain.agents import create_agent


class MailInfo(BaseModel):
    topic: str = Field(description="Topic of the email")
    email_body: str = Field(description="Clean email body")
    date: str = Field(description="Date of the email YYYY-MM-DD")
    mail_query_number: int = Field(description="Order number of the email in the chain")
    key_words: List[str] = Field(description="Important keywords")


class MailChainInfo(BaseModel):
    emails: List[MailInfo] = Field(description="Mail chain info")

In [5]:

agent = create_agent(
    model="deepseek-chat",
    tools=[],  # явно без инструментов
    response_format=MailChainInfo
)

In [9]:
query = """
SELECT
    id,
    sent_at_utc,
    body_text
FROM mailkb.emails_unique

LEFT ANTI JOIN mailkb.mail_parsed
ON emails_unique.id = mail_parsed.email_id

WHERE
    body_text IS NOT NULL
    AND length(body_text) > 30

ORDER BY sent_at_utc DESC
LIMIT 10
"""

df = client.query_df(query)

In [10]:
df

,id,sent_at_utc,body_text
0,8977d82a-f23a-47d7-9da9-537cd742d704,2021-02-28 20:22:34+00:00,Добрый день! Необходимо проставить оценку по ц...
1,47e3ef2c-9329-4ecb-9c46-925aedcebc9b,2021-02-28 20:02:00+00:00,—-—-—-— \nReply above this line. \n\nШэлиговск...
2,71c6e416-4956-42bc-ae42-09250ef28af0,2021-02-28 20:01:00+00:00,<https://www.gravatar.com/avatar/bc1100ceff6b...
3,8a07aa9e-303f-4b17-b729-0abb724219f7,2021-02-28 16:51:43+00:00,"Коллеги, добрый день\n\n \n\nПо данному вопрос..."
4,c73247b7-5efd-4b83-8082-74be467a32fa,2021-02-26 14:57:00+00:00,<https://www.gravatar.com/avatar/e6ebe0ca1152...
5,1ba5fb9f-edd8-44d3-bc3f-585c4987fff0,2021-02-26 14:41:01+00:00,—-—-—-— \nReply above this line. \n\nОстрик Пё...
6,a2d84c74-dcd7-4ac5-a942-2158f4be3b77,2021-02-26 14:12:00+00:00,—-—-—-— \nReply above this line. \n\nШарманов ...
7,c85daa0b-5eca-41e3-84ff-021be5a91798,2021-02-26 13:59:00+00:00,—-—-—-— \nReply above this line. \n\nСафина Ай...
8,224247aa-f10f-44fe-89f7-ce1d9e054da3,2021-02-26 13:58:00+00:00,<https://www.gravatar.com/avatar/1701f769b237...
9,ca0eb357-e8c3-4b76-b3bc-9696d9e23fbd,2021-02-26 13:41:02+00:00,<https://www.gravatar.com/avatar/572b97488d33...

In [11]:
results = []

for i in range(len(df)):
    body = df["body_text"][i]

    result = agent.invoke({
        "messages": [
            {
                "role": "user",
                "content": f"""
Начни обработку письма.

Извлеки структуру переписки.

EMAIL BODY:
{body}
"""
            }
        ]
    })

    structured = result["structured_response"]
    parsed_json = structured.model_dump_json()

    results.append({
        "email_id": df["id"][i],
        "parsed_json": parsed_json
    })

In [12]:
results

[{'email_id': '8977d82a-f23a-47d7-9da9-537cd742d704',
  'parsed_json': '{"emails":[{"topic":"Оценка стажера Генисаретский Сергей Сергеевич","email_body":"Добрый день! Необходимо проставить оценку по целям за 6 месяцев работы стажера Генисаретский Сергей Сергеевич и подтвердить его готовность к стажерской панели.\\n\\nПерейти в 1С:Документооборот <https://do.bearingpoint.ru/do/ru_RU//#e1cib/data/Документ.ОценкаСтажеров?ref=812b000c291ff2d711eaf083ed3b81f5> \\n\\nС уважением,\\n\\nОтдел по управлению персоналом","date":"2024-01-01","mail_query_number":1,"key_words":["оценка","стажер","Генисаретский Сергей Сергеевич","6 месяцев","цели","стажерская панель","1С:Документооборот","управление персоналом"]}]}'},
 {'email_id': '47e3ef2c-9329-4ecb-9c46-925aedcebc9b',
  'parsed_json': '{"emails":[{"topic":"Настройка профиля SAPSP-18265","email_body":"Коллеги, профиль настроили?\\n\\nView request <http://192.168.210.55:8080/servicedesk/customer/portal/2/SAPSP-18265?sda_source=notification-email>  · Turn off this request\'s notifications <http://192.168.210.55:8080/servicedesk/customer/portal/2/SAPSP-18265/unsubscribe?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJxc2giOiIxZTJmMDg2ZmEwZjA2ZjU4MjUxYjcwODc3YzlhOTAwZWYzMTI5NGMzMjg4MTMwN2U2OTVmMzI2ZTk3YzYyYzQxIiwiaXNzIjoic2VydmljZWRlc2stand0LXRva2VuLWlzc3VlciIsImNvbnRleHQiOnsidXNlciI6IkpJUkFVU0VSMTAwODUiLCJpc3N1ZSI6IlNBUFNQLTE4MjY1In0sImV4cCI6MTYxNjk2MTY5NiwiaWF0IjoxNjE0NTQyNDk2fQ.bVFipbNX9ddEInBKHtWCVDq9Zk6KjlMMZY4NT5DAOMo>","date":"2021-02-28","mail_query_number":1,"key_words":["профиль","настроили","SAPSP-18265","запрос","Jira Service Desk"]}]}'},
 {'email_id': '71c6e416-4956-42bc-ae42-09250ef28af0',
  'parsed_json': '{"emails":[{"topic":"Открыть доступ к поставкам Лесосибирского ЛДК","email_body":"Коллеги, профиль настроили?","date":"2024-01-01","mail_query_number":1,"key_words":["SAPSP-18265","доступ","поставки","Лесосибирский ЛДК","профиль","настроили"]}]}'},
 {'email_id': '8a07aa9e-303f-4b17-b729-0abb724219f7',
  'parsed_json': '{"emails":[{"topic":"еще раз про логистику","email_body":"Хочу уточнить в части расходов на логистику: у нас стоит задача отражать расходы на логистику месяц в месяц, но относится это не столько к своевременному отражению в системе счетов, которые выставлены транспортными компаниями в теущем месяце, сколько к отражению в текущем месяце расходов по транспортировке отгруженной в текужем месяце продукции. Т.е. если товар ушел в этом месяце, то и расходы на логистику мы должны отразить в этом месяце, даже если компания выставила нам счет следующим месяцем.\\n\\nВозможно будет такой подход реализовать в SAP?","date":"2020-11-25","mail_query_number":1,"key_words":["логистика","расходы","транспорт","отражение затрат","SAP","начисления","месяц отгрузки"]},{"topic":"RE: еще раз про логистику","email_body":"Коллеги\\n\\nВновь поднимается вопрос начислений по транспортным расходам\\nПоследний раз, когда мы обсуждали этот вопрос по филиалу ВФК выяснили, что принятое решение не позволяет делать такие начисления, но вы взяли время подумать . \\nЕсть ли какие-то идеи по этому вопросу?","date":"2020-11-25","mail_query_number":2,"key_words":["начисления","транспортные расходы","ВФК","решение","вопрос","идеи"]},{"topic":"RE: еще раз про логистику","email_body":"+ Алексей, Валентин. У вас есть история вопроса?","date":"2020-11-25","mail_query_number":3,"key_words":["история вопроса","Алексей","Валентин"]},{"topic":"RE: еще раз про логистику","email_body":"Татьяна\\n\\nУ нас была встреча в сентябре\\nПетр фиксировал итоги (письмо во вложении). В п.1 мы обозначили риск, который реализуется при запуске СЦБК в виду большого объема жд перевозок.\\nЭтот же вопрос уже поднимали при закрытии ВФК.\\nИ в сентябре мы как-то же сделали начисление по транспортным услугам в УК.","date":"2020-11-25","mail_query_number":4,"key_words":["встреча","сентябрь","риск","СЦБК","жд перевозки","ВФК","начисление","транспортные услуги","УК"]},{"topic":"RE: еще раз про логистику","email_body":"Виталий, добрый день,\\n\\nПросьба уточнить насколько детально надо делать начисления. Т.е. в разрезе каких аналитик (контрагент, сбытовой заказ, отгрузка итп)\\nЕсть ли уже существующий алгоритм из 1С? Просьба его прислать.\\nОткуда правильно брать плановую сумму начислений?\\n\\nПотом обсудим с FI как технически реализовать.","date":"2020-11-25","mail_query_number":5,"key_words":["начисления","аналитики","контрагент","сбытовой заказ","отгрузка","алгоритм","1С","плановая сумма","FI","техническая реализация"]},{"topic":"RE: еще раз про логистику","email_body":"Подключаю к переписке Горбунову Ирину.\\n\\nИрина, прошу прокомментировать вопросы.","date":"2020-11-25","mail_query_number":6,"key_words":["Горбунова Ирина","комментарий","вопросы"]},{"topic":"RE: еще раз про логистику","email_body":"Добрый день!\\n\\nНам начисления необходимы по группе номенклатуры, по рынкам (экспорт/вн.рынок, ВГО/сторонние) и виду транспорта. Информация необходима для формирования отчетов п выручке, в т.ч. очищенной от транспортной составляющей.\\n\\nВ 1С при формировании документа отгрузки в отдельной закладке указывался вид транспорта, плечо доставки и планируемая стоимость доставки. При получении фактического документа от транспортной компании делалась привязка ПТУ к документу отгрузки.\\n\\nДима, если что-то некорректно, поправь, пожалуйста.","date":"2020-11-25","mail_query_number":7,"key_words":["начисления","группа номенклатуры","рынки","экспорт","внутренний рынок","ВГО","сторонние","вид транспорта","отчеты","выручка","очищенная от транспорта","1С","отгрузка","плечо доставки","плановая стоимость","ПТУ"]},{"topic":"RE: еще раз про логистику","email_body":"Коллеги, добрый день,\\n\\nПросьба более развернуто пояснить:\\nЧто имеется ввиду под группой номенклатуры? Желательно прислать номера классов для каждого комбината (ВФК, ВФК ЛР, СЦБК, СЦБК ЛР, СУ, СУ Сальск, ЛЛДК, ЛЛДК ЛР).\\n\\nИтого, алгоритм на текущий момент следующий:\\n1) В отчете (нужно будет уточнить в каком) выгружаем отпущенные (отгруженные) поставки, по которым еще не разнесены счета на логистические услуги с маршрутами и плановыми стоимостями перевозки \\n2) Сворачиваем строки по аналитикам (экспорт/вн.рынок, ВГО/сторонние)\\n3) Вручную или через загрузчик проводим в FI начисления\\n4) Сторнируем проведенные начисления в начале следующего периода\\nСтоимость перевозок берем плановую из маршрутов.\\nОграничение:\\nНачисления не рассчитываются для АРКА.\\n\\nPS Петр, просьба в эту переписку сбросить виды транспорта, заложенные в справочник SAP.","date":"2020-11-26","mail_query_number":8,"key_words":["группа номенклатуры","номера классов","комбинаты","ВФК","СЦБК","СУ","ЛЛДК","алгоритм","отчет","отпущенные поставки","логистические услуги","маршруты","плановая стоимость","аналитики","FI","начисления","сторнирование","АРКА","виды транспорта","справочник SAP"]},{"topic":"RE: еще раз про логистику","email_body":"Нам транспортные по АРКЕ тоже нужны.\\n\\nНоменклатуры по СЦБК направит Марчик Юлия.","date":"2020-11-26","mail_query_number":9,"key_words":["транспортные","АРКА","нужны","номенклатуры","СЦБК","Марчик Юлия"]},{"topic":"RE: еще раз про логистику","email_body":"Добрый день.\\nНоменклатуры по СЦБК во вложении","date":"2020-11-26","mail_query_number":10,"key_words":["номенклатуры","СЦБК","вложение"]},{"topic":"RE: еще раз про логистику","email_body":"Коллеги, добрый день\\n\\nПо данному вопросу были какие-то дальнейшие действия или решения? Вопрос актуален и существенен с точки зрения отражения полноты затрат в периоде и корректного расчета выручки очищенной от транспорта.","date":"2020-11-26","mail_query_number":11,"key_words":["вопрос","дальнейшие действия","решения","актуален","отражение затрат","период","расчет выручки","очищенная от транспорта"]}]}'},
 {'email_id': 'c73247b7-5efd-4b83-8082-74be467a32fa',
  'parsed_json': '{"emails":[{"topic":"Замечание ОПЭ СЦБК №62","email_body":"Тимофей Алексеевич Кучкин назначил на Тимофей Алексеевич Кучкин\\n\\nSAP Support / SAPSP-17588 Замечание ОПЭ СЦБК №62\\n\\nКем изменено: Тимофей Алексеевич Кучкин\\nИсполнитель: Острик Пётр Тимофей Алексеевич Кучкин\\n\\nЭто сообщение отправлено из Atlassian Jira (v8.13.0#813000-sha1:8c68d80)","date":"2024-01-01","mail_query_number":1,"key_words":["SAPSP-17588","Замечание ОПЭ СЦБК №62","Тимофей Алексеевич Кучкин","Острик Пётр","Jira","назначение"]}]}'},
 {'email_id': '1ba5fb9f-edd8-44d3-bc3f-585c4987fff0',
  'parsed_json': '{"emails":[{"topic":"Заявка SAPSP-18530: Изменение статуса на \'Решен\'","email_body":"Острик Пётр changed the status to Решен.\\n\\nОстрик Пётр resolved this as Готово.\\n\\nView request <http://192.168.210.55:8080/servicedesk/customer/portal/2/SAPSP-18530?sda_source=notification-email>  · Turn off this request\'s notifications <http://192.168.210.55:8080/servicedesk/customer/portal/2/SAPSP-18530/unsubscribe?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJxc2giOiIwZTczOTdlYzUzMmFkMTJiYjliMjFmYjU1MWFlZTFkMDM2MTI0ZWZhMjBmYWVjODkzMmQ2Y2ZiMjJjZGE0MjEyIiwiaXNzIjoic2VydmljZWRlc2stand0LXRva2VuLWlzc3VlciIsImNvbnRleHQiOnsidXNlciI6IkpJUkFVU0VSMTAwODUiLCJpc3N1ZSI6IlNBUFNQLTE4NTMwIn0sImV4cCI6MTYxNjc2OTYyOSwiaWF0IjoxNjE0MzUwNDI5fQ.8zdicZybmWbjdaLUzZ6VYHNvvTOF1ip-7eFBOe9pXdo>\\n\\nThis is shared with pustovitova_ns@segezha-group.com, Шэлиговска Елена Александровна и Острик Пётр.\\n\\nЦентр поддержки, powered by Jira Service Desk <https://www.atlassian.com/software/jira/service-desk/powered-by?utm_medium=email&utm_source=service-desk_email-notification_server&utm_campaign=service-desk_email-notification_server> , sent you this message.","date":"2021-02-25","mail_query_number":1,"key_words":["SAPSP-18530","Решен","Готово","Острик Пётр","Jira Service Desk","заявка","статус"]}]}'},
 {'email_id': 'a2d84c74-dcd7-4ac5-a942-2158f4be3b77',
  'parsed_json': '{"emails":[{"topic":"Автоматическое распределение поставок в EWM","email_body":"Сделано. Все исходящие поставки при отгрузке бумаги с запланированными транспортировками будут автоматически распределяться в EWM начиная с 17:26 26.02.2021 по Москве. Распределение поставок в EWM будет автоматически выполняться каждые пол часа.","date":"2021-02-26","mail_query_number":1,"key_words":["автоматическое распределение","EWM","поставки","отгрузка бумаги","транспортировки","каждые пол часа"]}]}'},
 {'email_id': 'c85daa0b-5eca-41e3-84ff-021be5a91798',
  'parsed_json': '{"emails":[{"topic":"Заявка SAPSP-18554: Изменение статуса на \'Решен\'","email_body":"Сафина Айгуль Рифатовна changed the status to Решен. Сафина Айгуль Рифатовна resolved this as Готово. Сафина Айгуль Рифатовна commented: Готово. View request <http://192.168.210.55:8080/servicedesk/customer/portal/2/SAPSP-18554?sda_source=notification-email>  · Turn off this request\'s notifications <http://192.168.210.55:8080/serviced/servicedesk/customer/portal/2/SAPSP-18554/unsubscribe?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJxc2giOiIyNzhkOTVhNDA3MGQxZjM1MTdhYzFjMjQ0ZTM5NTRkZDg1NzI1ODEzYTdhOTgyYWUwMzk5MjBhMWNiYjc0NzM3IiwiaXNzIjoic2VydmljZWRlc2stand0LXRva2VuLWlzc3VlciIsImNvbnRleHQiOnsidXNlciI6IkpJUkFVU0VSMTAwODUiLCJpc3N1ZSI6IlNBUFNQLTE4NTU0In0sImV4cCI6MTYxNjc2NzExNiwiaWF0IjoxNjE0MzQ3OTE2fQ.fk-8I5uo8jSvnJdaHGZYbnZjPniSnccuU3D0BBqXDZo>  This is shared with pustovitova_ns@segezha-group.com, Сафина Айгуль Рифатовна, Острик Пётр и Дондуков Иван. Центр поддержки, powered by Jira Service Desk <https://www.atlassian.com/software/jira/service-desk/powered-by?utm_medium=email&utm_source=service-desk_email-notification_server&utm_campaign=service-desk_email-notification_server> , sent you this message.","date":"2021-02-25","mail_query_number":1,"key_words":["SAPSP-18554","Решен","Готово","Сафина Айгуль Рифатовна","Jira Service Desk","заявка","статус"]}]}'},
 {'email_id': '224247aa-f10f-44fe-89f7-ce1d9e054da3',
  'parsed_json': '{"emails":[{"topic":"Завершение запроса SAPSP-18554","email_body":"Готово.\\n\\nSAP Support / SAPSP-18554 SAPSP-18554\\n6100049111\\nКем изменено: Сафина Айгуль Рифатовна\\nИсполнитель: Острик Пётр\\nРешение: Готово\\nСтатус: В работе Решен\\n\\nЭто сообщение отправлено из Atlassian Jira (v8.13.0#813000-sha1:8c68d80)","date":"2024-01-01","mail_query_number":1,"key_words":["SAPSP-18554","Готово","Сафина Айгуль Рифатовна","Острик Пётр","6100049111","Решен","Jira"]}]}'},
 {'email_id': 'ca0eb357-e8c3-4b76-b3bc-9696d9e23fbd',
  'parsed_json': '{"emails":[{"topic":"Назначение задачи SAPSP-18554","email_body":"Анисимов Василий назначил на Острик Пётр\\n\\nSAP Support / SAPSP-18554\\n6100049111\\nКем изменено: Анисимов Василий\\nИсполнитель: Анисимов Василий Острик Пётр\\n\\nЭто сообщение отправлено из Atlassian Jira (v8.13.0#813000-sha1:8c68d80)","date":"2024-01-01","mail_query_number":1,"key_words":["SAPSP-18554","Анисимов Василий","Острик Пётр","назначение","задача","Jira","6100049111"]}]}'}]

In [13]:

rows = [
    [r["email_id"], r["parsed_json"]]
    for r in results
]

client.insert(
    "mailkb.mail_parsed",
    rows,
    column_names=["email_id", "parsed_json"]
)

#### вариант 3 с параллельной обработкой

In [3]:
from pydantic import BaseModel, Field
from typing import List
from langchain.agents import create_agent
from concurrent.futures import ThreadPoolExecutor, as_completed
import pandas as pd


class MailInfo(BaseModel):
    topic: str = Field(description="Topic of the email")
    email_body: str = Field(description="Clean email body")
    date: str = Field(description="Date of the email YYYY-MM-DD")
    mail_query_number: int = Field(description="Order number of the email in the chain")
    key_words: List[str] = Field(description="Important keywords")


class ParsedEmailResult(BaseModel):
    email_id: str = Field(description="Original email id from the input batch")
    emails: List[MailInfo] = Field(description="Parsed content for this email")


class ParsedEmailBatch(BaseModel):
    items: List[ParsedEmailResult] = Field(description="Parsed results for all emails in the batch")


agent = create_agent(
    model="deepseek-chat",
    tools=[],
    response_format=ParsedEmailBatch
)


query = """
SELECT
    id,
    sent_at_utc,
    body_text
FROM mailkb.emails_unique

LEFT ANTI JOIN mailkb.mail_parsed
ON emails_unique.id = mail_parsed.email_id

WHERE
    body_text IS NOT NULL
    AND length(body_text) > 30

ORDER BY sent_at_utc DESC
LIMIT 30
"""

In [7]:

df = client.query_df(query)


def chunk_list(rows, batch_size):
    for i in range(0, len(rows), batch_size):
        yield rows[i:i + batch_size]


def build_batch_prompt(batch_rows):
    parts = []
    for idx, row in enumerate(batch_rows, start=1):
        body = (row["body_text"] or "")[:15000]
        parts.append(
            f"""
EMAIL #{idx}
email_id: {row["id"]}

EMAIL BODY:
{body}
""".strip()
        )

    return """
Начни обработку нескольких писем.

Для КАЖДОГО письма:
- извлеки структуру переписки,
- верни отдельный результат,
- обязательно сохрани правильный email_id,
- не смешивай письма между собой.

Верни результат для всех писем из входного батча.

{}
""".format("\n\n" + ("\n\n" + "=" * 80 + "\n\n").join(parts))


def process_batch(batch_rows):
    try:
        prompt = build_batch_prompt(batch_rows)

        result = agent.invoke({
            "messages": [
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        })

        structured = result["structured_response"]

        parsed_rows = []
        returned_ids = set()

        for item in structured.items:
            returned_ids.add(item.email_id)
            parsed_rows.append({
                "email_id": item.email_id,
                "parsed_json": item.model_dump_json()
            })

        # если модель не вернула часть писем — помечаем ошибкой
        requested_ids = {row["id"] for row in batch_rows}
        missing_ids = requested_ids - returned_ids

        error_rows = [
            {"email_id": mid, "error": "missing_in_model_response"}
            for mid in missing_ids
        ]

        return parsed_rows, error_rows

    except Exception as e:
        return [], [
            {"email_id": row["id"], "error": str(e)}
            for row in batch_rows
        ]

In [8]:

BATCH_SIZE = 3
MAX_WORKERS = 6

rows = df.to_dict("records")
batches = list(chunk_list(rows, BATCH_SIZE))

all_success = []
all_errors = []

with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
    futures = [executor.submit(process_batch, batch) for batch in batches]

    for future in as_completed(futures):
        success_rows, error_rows = future.result()
        all_success.extend(success_rows)
        all_errors.extend(error_rows)

print("success:", len(all_success))
print("errors:", len(all_errors))

success: 9
errors: 21

In [9]:

# успешные результаты — в ClickHouse
if all_success:
    insert_rows = [[r["email_id"], r["parsed_json"]] for r in all_success]
    client.insert(
        "mailkb.mail_parsed",
        insert_rows,
        column_names=["email_id", "parsed_json"]
    )

errors_df = pd.DataFrame(all_errors)

In [10]:
errors_df

,email_id,error
0,10532f64-e0f3-4e98-bf02-0297f70e4616,"Error code: 400 - {'error': {'message': ""An as..."
1,79cd1c4f-39b4-4d7e-9083-a8a2c81ffc88,"Error code: 400 - {'error': {'message': ""An as..."
2,1a94651d-9380-4794-9330-7eca2218f93f,"Error code: 400 - {'error': {'message': ""An as..."
3,036e6e6e-2313-480d-9915-bffa5e0d1c00,"Error code: 400 - {'error': {'message': ""An as..."
4,8c095f6d-fd68-41f7-920a-c0bcc8959d6f,"Error code: 400 - {'error': {'message': ""An as..."
5,fc461be4-400f-4138-b06d-62dbb1a36130,"Error code: 400 - {'error': {'message': ""An as..."
6,1b4a4ed5-d8d1-40b4-98dc-e8088bb1feab,"Error code: 400 - {'error': {'message': ""An as..."
7,d9f680a9-3ed4-4805-8488-23849334c7bc,"Error code: 400 - {'error': {'message': ""An as..."
8,bc9899a3-98ed-4044-aa38-f43604c9cf58,"Error code: 400 - {'error': {'message': ""An as..."
9,bd2f2c30-82d9-4f7e-a612-dde8407a0459,"Error code: 400 - {'error': {'message': ""An as..."
10,d8cb2d22-55a7-4a74-8597-7bab7eaf8d72,"Error code: 400 - {'error': {'message': ""An as..."
11,2e2cce99-e4de-426d-9f9a-6ce848c9d3b8,"Error code: 400 - {'error': {'message': ""An as..."
12,25a938cd-5675-45ff-aaa9-25f3035eaab7,"Error code: 400 - {'error': {'message': ""An as..."
13,8a4f0348-6c5c-4308-957b-34bb456868c4,"Error code: 400 - {'error': {'message': ""An as..."
14,baed7690-7f17-4d8d-a83d-2e29cbab8ace,"Error code: 400 - {'error': {'message': ""An as..."
15,2d96b799-23ab-4cec-a3b0-1cf7c3586a2b,"Error code: 400 - {'error': {'message': ""An as..."
16,a09bcc4e-be61-4781-88ba-f3c78118fa4d,"Error code: 400 - {'error': {'message': ""An as..."
17,19cc745e-81a1-4607-861b-bbbd106c9f0d,"Error code: 400 - {'error': {'message': ""An as..."
18,c7f5f7bb-1bb8-4885-a313-248ff91699e5,"Error code: 400 - {'error': {'message': ""An as..."
19,de3bf9d0-9165-4fca-8e8e-203d4331c43b,"Error code: 400 - {'error': {'message': ""An as..."
20,32ea4ca5-0367-4d67-8c41-dbf1bc5fd727,"Error code: 400 - {'error': {'message': ""An as..."

#### вариант 4 параллельная обработка без агента

In [11]:
from pydantic import BaseModel, Field
from typing import List


class MailInfo(BaseModel):
    topic: str
    email_body: str
    date: str
    mail_query_number: int
    key_words: List[str]


class ParsedEmailResult(BaseModel):
    email_id: str
    emails: List[MailInfo]


class ParsedEmailBatch(BaseModel):
    items: List[ParsedEmailResult]

In [12]:
from langchain.chat_models import init_chat_model

llm = init_chat_model(
    model="deepseek-chat",
    temperature=0
)

structured_llm = llm.with_structured_output(ParsedEmailBatch)

In [13]:
def build_batch_prompt(batch_rows):
    parts = []

    for idx, row in enumerate(batch_rows, start=1):
        body = (row["body_text"] or "")[:15000]

        parts.append(
            f"""
EMAIL #{idx}
email_id: {row["id"]}

EMAIL BODY:
{body}
""".strip()
        )

    return f"""
Начни обработку нескольких писем.

Для КАЖДОГО письма:
- извлеки структуру переписки
- верни результат отдельно
- ОБЯЗАТЕЛЬНО укажи email_id
- не смешивай письма между собой

Верни результат в формате ParsedEmailBatch.

{chr(10).join(parts)}
"""

In [14]:
import time


def call_with_retry(prompt, max_retries=3):

    for attempt in range(max_retries):
        try:
            return structured_llm.invoke(prompt)

        except Exception as e:
            print(f"Retry {attempt+1} due to error:", e)
            time.sleep(1.5 * (attempt + 1))

    raise Exception("LLM failed after retries")

In [15]:
def process_batch(batch_rows):

    prompt = build_batch_prompt(batch_rows)

    try:
        structured = call_with_retry(prompt)

        parsed_rows = []
        returned_ids = set()

        for item in structured.items:
            returned_ids.add(item.email_id)

            parsed_rows.append({
                "email_id": item.email_id,
                "parsed_json": item.model_dump_json()
            })

        requested_ids = {row["id"] for row in batch_rows}
        missing_ids = requested_ids - returned_ids

        error_rows = [
            {"email_id": mid, "error": "missing_in_response"}
            for mid in missing_ids
        ]

        return parsed_rows, error_rows

    except Exception as e:
        return [], [
            {"email_id": row["id"], "error": str(e)}
            for row in batch_rows
        ]

In [16]:
from concurrent.futures import ThreadPoolExecutor, as_completed


def chunk_list(rows, batch_size):
    for i in range(0, len(rows), batch_size):
        yield rows[i:i + batch_size]


query = """
SELECT
    id,
    sent_at_utc,
    body_text
FROM mailkb.emails_unique

LEFT ANTI JOIN mailkb.mail_parsed
ON emails_unique.id = mail_parsed.email_id

WHERE
    body_text IS NOT NULL
    AND length(body_text) > 30

ORDER BY sent_at_utc DESC
LIMIT 50
"""

df = client.query_df(query)

rows = df.to_dict("records")

BATCH_SIZE = 3
MAX_WORKERS = 6

batches = list(chunk_list(rows, BATCH_SIZE))

all_success = []
all_errors = []

with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:

    futures = [executor.submit(process_batch, b) for b in batches]

    for future in as_completed(futures):
        success_rows, error_rows = future.result()

        all_success.extend(success_rows)
        all_errors.extend(error_rows)

print("SUCCESS:", len(all_success))
print("ERRORS:", len(all_errors))

Retry 1 due to error: Function ParsedEmailBatch arguments:

{"items": [{"email_id": "10532f64-e0f3-4e98-bf02-0297f70e4616", "emails": [{"topic": "ошибки ТМ", "email_body": "Посмотрела все нечаянно )\n\nПо транспореону написала письмо Шэлиговска.\n\nПо остальным отменила, а ошибки по iso код обработал Сергей Г.\n\n \n\nFrom: Ostrik Petr \nSent: Wednesday, February 17, 2021 2:31 PM\nTo: Safina Aygul <aygul.safina@bearingpoint.ru>\nSubject: FW: ошибки ТМ\n\n \n\nПосмотри плз Транспореон\n\n \n\nFrom: Pinkhasov Dmitriy(CE) \nSent: Thursday, February 11, 2021 11:30 PM\nTo: Ostrik Petr <petr.ostrik@bearingpoint.ru <mailto:petr.ostrik@bearingpoint.ru> >\nSubject: RE: ошибки ТМ\n\n \n\nПривет\n\n \n\nПосмотри пжл ошибки в STP\n\nПо TRANSPOREON\n\n36D4EBF361FD11EB80E300000C24F6BA\n\nC7A7C644647611EB847000000C24F6BA\n\n45714745651D11EB914F00000C24F6BB\n\nBA8BE2B0655F11EBB37C00000C24F6BA\n\n70531C27663211EB8A1F00000C24F6BA\n\n32258A5366B411EB9F4A00000C24F6BB\n\n35CC95BD66B411EBC5E500000C24F6BB\n\n38CC5AD166B411EB927900000C24F6BA\n\n3BF7A76266B411EB95E100000C24F6BB\n\n2CD8B77C66D011EB97E900000C24F6BB\n\n3165755A66D011EBBE0C00000C24F6BA\n\n18E2AF1669D811EBBFA500000C24F6BB\n\nB598C39A6AE911EBA7C900000C24F6BA\n\n31BF8DA26B7611EBCD1F00000C24F6BB\n\n320BBE3C6B7611EBA9F000000C24F6BA\n\n78E8574F6C3511EB9EA600000C24F6BA\n\n \n\nИз ERP\n\n0050560174E21EEB98BD67FFD8572499\n\n0050560174E71EEB98DBAA0D76AF2639\n\n0050560174E71EEB98DC228731DBA64E\n\n0050560174E71EDB999F61A934B48253\n\n0050560174E21EEB99BEE0EE35E995F8\n\n0050560174E21EEB99C0467D57205769\n\n0050560174E21EEB99C0EEA351DA3854\n\n0050560174E21EDB99D37DFDF3E74264\n\n0050560174E71EEB99D53D272E81CDD8\n\n0050560174E21EDB99D619F72DE043F6\n\n0050560174E21EDB99D67148FEFA04A9\n\n0050560174E71EEB99D6C7E4C8394FC9\n\n0050560174E71EEB99D87A4F3A21B24A\n\n0050560174E71EEB99DC1DB44A92159A\n\n0050560174E71EEB99EB3094A83FDADF\n\n0050560174E71EEB99EC3022EFFC9B40\n\n0050560174E21EDB99F265DFF356F772\n\n0050560174E71EDB9B8B3E68A3CE8819\n\n0050560174E21EDB9B8B3EC794C2F8EA\n\n0050560174E21EDB9B8B41C65129F8EB\n\n0050560174E71EDB9B8B5787730C0823\n\n0050560174E71EDB9B8BEB8D76D20885\n\n0050560174E71EDB9B8CCE62756448EB\n\n0050560174E21EDB9B8DEC590A057AB2\n\n \n\nВ SEP тоже куча ошибок в сообщениях от TM. С Щетининым начали разбирать, но исправили не всё.\n\n \n\nНазначь пжл ответственного и  чтоб обработать или отменить старые сообщения. Напоминаю, что в TM работает авторестрт и лог сообщений растет очень быстро, делая сообщения нечитаемыми.\n\n \n\nFrom: Pinkhasov Dmitriy(CE) \nSent: Saturday, January 16, 2021 2:01 PM\nTo: Ostrik Petr <petr.ostrik@bearingpoint.ru <mailto:petr.ostrik@bearingpoint.ru> >\nSubject: RE: ошибки ТМ\n\n \n\nВ SEP тоже куча ошибок в сообщениях от TM. С этими ошибками к тебе, назначишь ответственного ?\n\n0050560174071EEAAB9C8DC92C659F6D\n\n0050560174071EEAAB9C8DC92C669F6D\n\n0050560174071EDAAEF6E469F055F1DA\n\n0050560174071EDAAFF03BE0A8F71895\n\n0050560174071EDAAFF20D380D2978A2\n\n0050560174071EDAB086959475ED394E\n\n0050560174071EDAB0886C0F98D0795D\n\n0050560174071EDAB0A1A9070B6E9A3F\n\n0050560174071EEAB39C20462C54D1EC\n\n0050560174071EEAB49B9A1179F71955\n\n0050560174071EDAB5F75B7B29BCEABA\n\n0050560174071EDAB6DDBF5C6FC2336F\n\n0050560174071EDAB6DDBFD8B1A0B36F\n\n0050560174071EDAB6DDC18DF2AC336F\n\n0050560174071EDAB6DDC1E600CFB36F\n\n0050560174071EDAB78F4F9296F197AD\n\n0050560174071EDAB78F5377820CF7AD\n\n0050560174071EDAB790159692BD77BA\n\n0050560174071EEAB88A3FF4090BC02C\n\n0050560174071EEAB8D709E4F1BB24C0\n\n0050560174071EEAB8F3976B81F24660\n\n0050560174071EEAB8F47FB13B90C665\n\n0050560174071EEAB8F48D6E94B04665\n\n0050560174071EEAB9BB75304212C856\n\n0050560174071EEAB9BC4AA567EF4866\n\n0050560174071EEABA887237D8CA4BFD\n\n0050560174071EEABBB8BE9509D2D3F0\n\n0050560174071EEABCB57F1AEBC7F8AF\n\n0050560174071EEABCB8A6BED0BDB8D3\n\n0050560174071EDABE95E94EB24D96BD\n\n0050560174071EDABEB0BA6B6849BCC2\n\n0050560174071EDABEB30B1E26EEBD2D\n\n0050560174071EEABEFF6B72DE11CA8E\n\n0050560174071EEB80CCBFFC2FEAA353\n\n0050560174071EEB82AB72647569A3C9\n\n0050560174071EEB82AB73E1B8F283C9\n\n0050560174071EEB82C33F2DA96B09BC\n\n0050560174071EEB838BFBCB6E645147\n\n0050560174071EEB83A3C932710ED3CA\n\n0050560174071EEB83A8F6DFC96A945C\n\n0050560174071EDB84BEC1D440580BB9\n\n0050560174071EDB84BF72F46F98EBD5\n\n0050560174071EDB84C068DFA4DC2BFA\n\n0050560174071EDB84DB6D199FADD062\n\n0050560174071EDB858650407E2D76F2\n\n0050560174071EDB859F233F509AFA33\n\n0050560174071EDB85A739B0AFAA5B21\n\n0050560174071EEB8683AFBC5154240D\n\n0050560174071EEB8683F1DC1A78A415\n\n0050560174071EEB868CCF0C922D8556\n\n0050560174071EEB86A1FCFB5942C66C\n\n0050560174071EEB86B5C8773E7C0775\n\n0050560174071EEB86D42F2E88FF0900\n\n0050560174071EEB86D582A1BF5C0913\n\n0050560174071EEB88816BDDC85D7365\n\n0050560174071EEB88E7BA626C1CFC28\n\n0050560174071EEB88FDD796F9C8FE8D\n\n0050560174071EEB898331F9A1C23F12\n\n0050560174071EDB8997C1F72102E108\n\n0050560174071EDB89B34B30A92DA6B4\n\n0050560174071EDB89B3E0DCB20546D0\n\n0050560174071EEB8AD87BE6C2C36892\n\n0050560174071EEB8AE28911F54A4AAF\n\n0050560174071EEB8AE3F9240645AAF2\n\n0050560174071EDB8BFC24DC194D951F\n\n0050560174071EDB8C96653427C43909\n\n0050560174071EEB8CC869D7D88A6A34\n\n0050560174071EEB8CC9033FCE082A62\n\n0050560174071EEB8CC96834CAEDCA84\n\n0050560174071EEB8CCEF6E4857B6CD1\n\n0050560174071EEB8CE24A9D1297127F\n\n0050560174071EEB8CF83046003ED722\n\n0050560174071EEB8CFE43E341C4B84F\n\n0050560174071EEB8CFF6CCE97AF78A5\n\n0050560174071EEB8D8E73FAB45DFBEC\n\n0050560174071EEB8D8F7CA9CB2DDC29\n\n0050560174071EEB8D910A472B141C6C\n\n0050560174071EEB8D9899283C301E23\n\n0050560174071EEB8D98A3736355DE27\n\n0050560174071EEB8D9947BA1F15BE50\n\n0050560174071EEB8D995DDD5CCD1E56\n\n0050560174071EEB8D997068D35D1E5A\n\n0050560174071EEB8D997F44583BBE5E\n\n0050560174071EDB8DA390C863CC4115\n\n0050560174071EDB8DA39A87F7B54118\n\n0050560174071EDB8DA3A31779B9211B\n\n0050560174071EDB8DA3AAD6FB54211E\n\n0050560174071EDB8DA3B3422CF22120\n\n0050560174071EDB8DA3BDB2E4344121\n\n0050560174071EDB8DA3C641C9DA4123\n\n0050560174071EDB8DA3D080154A4125\n\n0050560174071EDB8DA3D90D60BE4127\n\n0050560174071EDB8DA3E7F9B0F1412A\n\n0050560174071EDB8DA3F073AC06812C\n\n0050560174071EDB8DA3F8911730C131\n\n0050560174071EDB8DA40086705BC134\n\n0050560174071EDB8DA4086F51154137\n\n0050560174071EDB8DA41C3D7F99E13E\n\n0050560174071EDB8DA88A11FA7AA2A3\n\n0050560174071EDB8DAA833919712374\n\n0050560174071EDB8DABEB65C2D144DA\n\n0050560174071EDB8DC1639DCF5552BC\n\n0050560174071EDB8DC5593F7787537B\n\n0050560174071EDB8DC5737B82525382\n\n0050560174071EDB8DC579E11D84F384\n\n0050560174071EDB8DDB686D758B3A5A\n\n0050560174071EDB8DDB7747A9D41A5D\n\n0050560174071EEB8EA3B3C4E9636EE5\n\n0050560174071EEB8EAB0BFFAA4F308A\n\n0050560174071EEB8ED6C96D7A1A9B7B\n\n0050560174071EEB8ED6C984B8EF7B7B\n\n0050560174071EEB8ED6CF7C437D3B7C\n\n0050560174071EEB8ED73F47B898FB9E\n\n0050560174071EEB8EDC18671A28BD7A\n\n0050560174071EEB8EDC1BDA43C2FD7A\n\n0050560174071EEB8EDCBA01FC01FD9F\n\n0050560174071EEB8FBE29306DD0C135\n\n0050560174071EEB8FED5F6A410C8FE6\n\n0050560174071EEB908B193D068292AD\n\n0050560174071EEB90A2306D98E5F53C\n\n0050560174071EEB90A3EACBB7A2755D\n\n0050560174071EEB90A9996BFD4315ED\n\n0050560174071EDB9185D200B010E360\n\n0050560174071EDB9185FB33DD84E361\n\n0050560174071EDB918A39F1AEDF43EB\n\n0050560174071EDB918A3EF85A9483EC\n\n0050560174071EDB918AAA135C8AE3F6\n\n0050560174071EDB918CCB6209C54437\n\n0050560174071EDB91D4F1D290E3AEAD\n\n0050560174071EDB91D6EA5FDDC92EEB\n\n0050560174071EDB91D6EA917A5BCEEB\n\n0050560174071EEB92B9B02307A642A2\n\n0050560174071EEB92D117F0239F6738\n\n0050560174071EDB93CF19A2138EC093\n\n0050560174071EEB959CA316DB4D0494\n\n0050560174071EEB95AD0892030327F6\n\n0050560174071EEB95ADEAEB49EE6827\n\n0050560174071EEB95C7EE665F048DC5\n\n0050560174071EEB95CED26D77A9AF43\n\n0050560174071EEB95CF7EFB4627AF68\n\n \n\nFrom: Pinkhasov Dmitriy(CE) \nSent: Friday, January 15, 2021 7:37 PM\nTo: Ostrik Petr <petr.ostrik@bearingpoint.ru <mailto:petr.ostrik@bearingpoint.ru> >\nSubject: RE: ошибки ТМ\n\n \n\nПосмотри пжл еще по Транспореону\n\n02F05EAA557B11EB9B3F00000C24F71F\n\n033FF456557B11EB85A100000C24F71E\n\n37ACCF70565811EBA84900000C24F71F\n\n37DFC75F565811EB8FC100000C24F71E\n\n \n\nFrom

are not valid JSON. Received JSONDecodeError Unterminated string starting at: line 1 column 113 (char 112)
For troubleshooting, visit: https://docs.langchain.com/oss/python/langchain/errors/OUTPUT_PARSING_FAILURE
For troubleshooting, visit: https://docs.langchain.com/oss/python/langchain/errors/OUTPUT_PARSING_FAILURE
Retry 1 due to error: Function ParsedEmailBatch arguments:


KeyboardInterrupt:

In [ ]:
if all_success:
    insert_rows = [
        [r["email_id"], r["parsed_json"]]
        for r in all_success
    ]

    client.insert(
        "mailkb.mail_parsed",
        insert_rows,
        column_names=["email_id", "parsed_json"]
    )

In [ ]:
import pandas as pd

errors_df = pd.DataFrame(all_errors)
# errors_df.to_csv("mail_errors.csv", index=False)